// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** @param id
  *  权限id
  * @param grant
  *  授权者，credit code或者rdid
  * @param granted
  *  操作权限的被授予者,credit code或者rdid
  * @param opId
  *  操作id
  * @param isTransfer
  *  TRANSFER_DISABLE 不能让渡；TRANSFER_ONCE 让渡一次；TRANSFER_REPEATEDLY 可以无限让渡
  * @param createTime
  *  建立时间
  * @param disableTime
  *  禁用时间
  * @param authorizeValid
  *  是否有效，默认有效，否则为禁用，值=false
  * @param version
  *  默认1.0
  */
@SerialVersionUID(0L)
final case class Authorize(
    id: _root_.scala.Predef.String = "",
    grant: _root_.scala.Predef.String = "",
    granted: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    opId: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    isTransfer: rep.proto.rc2.Authorize.TransferType = rep.proto.rc2.Authorize.TransferType.TRANSFER_DISABLE,
    createTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    disableTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    authorizeValid: _root_.scala.Boolean = false,
    version: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Authorize] with scalapb.lenses.Updatable[Authorize] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = grant
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      granted.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
      }
      opId.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
      }
      
      {
        val __value = isTransfer
        if (__value != rep.proto.rc2.Authorize.TransferType.TRANSFER_DISABLE) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value.value)
        }
      };
      if (createTime.isDefined) {
        val __value = createTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (disableTime.isDefined) {
        val __value = disableTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = authorizeValid
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(8, __value)
        }
      };
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = grant
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      granted.foreach { __v =>
        val __m = __v
        _output__.writeString(3, __m)
      };
      opId.foreach { __v =>
        val __m = __v
        _output__.writeString(4, __m)
      };
      {
        val __v = isTransfer
        if (__v != rep.proto.rc2.Authorize.TransferType.TRANSFER_DISABLE) {
          _output__.writeEnum(5, __v.value)
        }
      };
      createTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(6, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      disableTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(7, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = authorizeValid
        if (__v != false) {
          _output__.writeBool(8, __v)
        }
      };
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(9, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.Authorize = {
      var __id = this.id
      var __grant = this.grant
      val __granted = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.granted)
      val __opId = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.opId)
      var __isTransfer = this.isTransfer
      var __createTime = this.createTime
      var __disableTime = this.disableTime
      var __authorizeValid = this.authorizeValid
      var __version = this.version
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __id = _input__.readString()
          case 18 =>
            __grant = _input__.readString()
          case 26 =>
            __granted += _input__.readString()
          case 34 =>
            __opId += _input__.readString()
          case 40 =>
            __isTransfer = rep.proto.rc2.Authorize.TransferType.fromValue(_input__.readEnum())
          case 50 =>
            __createTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __createTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 58 =>
            __disableTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __disableTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 64 =>
            __authorizeValid = _input__.readBool()
          case 74 =>
            __version = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.Authorize(
          id = __id,
          grant = __grant,
          granted = __granted.result(),
          opId = __opId.result(),
          isTransfer = __isTransfer,
          createTime = __createTime,
          disableTime = __disableTime,
          authorizeValid = __authorizeValid,
          version = __version,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withId(__v: _root_.scala.Predef.String): Authorize = copy(id = __v)
    def withGrant(__v: _root_.scala.Predef.String): Authorize = copy(grant = __v)
    def clearGranted = copy(granted = _root_.scala.Seq.empty)
    def addGranted(__vs: _root_.scala.Predef.String*): Authorize = addAllGranted(__vs)
    def addAllGranted(__vs: Iterable[_root_.scala.Predef.String]): Authorize = copy(granted = granted ++ __vs)
    def withGranted(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Authorize = copy(granted = __v)
    def clearOpId = copy(opId = _root_.scala.Seq.empty)
    def addOpId(__vs: _root_.scala.Predef.String*): Authorize = addAllOpId(__vs)
    def addAllOpId(__vs: Iterable[_root_.scala.Predef.String]): Authorize = copy(opId = opId ++ __vs)
    def withOpId(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Authorize = copy(opId = __v)
    def withIsTransfer(__v: rep.proto.rc2.Authorize.TransferType): Authorize = copy(isTransfer = __v)
    def getCreateTime: com.google.protobuf.timestamp.Timestamp = createTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearCreateTime: Authorize = copy(createTime = _root_.scala.None)
    def withCreateTime(__v: com.google.protobuf.timestamp.Timestamp): Authorize = copy(createTime = Option(__v))
    def getDisableTime: com.google.protobuf.timestamp.Timestamp = disableTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearDisableTime: Authorize = copy(disableTime = _root_.scala.None)
    def withDisableTime(__v: com.google.protobuf.timestamp.Timestamp): Authorize = copy(disableTime = Option(__v))
    def withAuthorizeValid(__v: _root_.scala.Boolean): Authorize = copy(authorizeValid = __v)
    def withVersion(__v: _root_.scala.Predef.String): Authorize = copy(version = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = grant
          if (__t != "") __t else null
        }
        case 3 => granted
        case 4 => opId
        case 5 => {
          val __t = isTransfer.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 6 => createTime.orNull
        case 7 => disableTime.orNull
        case 8 => {
          val __t = authorizeValid
          if (__t != false) __t else null
        }
        case 9 => {
          val __t = version
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(id)
        case 2 => _root_.scalapb.descriptors.PString(grant)
        case 3 => _root_.scalapb.descriptors.PRepeated(granted.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 4 => _root_.scalapb.descriptors.PRepeated(opId.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 5 => _root_.scalapb.descriptors.PEnum(isTransfer.scalaValueDescriptor)
        case 6 => createTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 7 => disableTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 8 => _root_.scalapb.descriptors.PBoolean(authorizeValid)
        case 9 => _root_.scalapb.descriptors.PString(version)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.Authorize
}

object Authorize extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.Authorize] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.Authorize] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.Authorize] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.Authorize(
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        grant = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        granted = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        opId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        isTransfer = rep.proto.rc2.Authorize.TransferType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.Authorize.TransferType.TRANSFER_DISABLE.scalaValueDescriptor).number),
        createTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        disableTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        authorizeValid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 6 => __out = com.google.protobuf.timestamp.Timestamp
      case 7 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 5 => rep.proto.rc2.Authorize.TransferType
    }
  }
  lazy val defaultInstance = rep.proto.rc2.Authorize(
    id = "",
    grant = "",
    granted = _root_.scala.Seq.empty,
    opId = _root_.scala.Seq.empty,
    isTransfer = rep.proto.rc2.Authorize.TransferType.TRANSFER_DISABLE,
    createTime = _root_.scala.None,
    disableTime = _root_.scala.None,
    authorizeValid = false,
    version = ""
  )
  sealed trait TransferType extends _root_.scalapb.GeneratedEnum {
    type EnumType = TransferType
    def isTransferDisable: _root_.scala.Boolean = false
    def isTransferOnce: _root_.scala.Boolean = false
    def isTransferRepeatedly: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[TransferType] = rep.proto.rc2.Authorize.TransferType
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.Authorize.TransferType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.Authorize.TransferType.Recognized])
  }
  
  object TransferType extends _root_.scalapb.GeneratedEnumCompanion[TransferType] {
    sealed trait Recognized extends TransferType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[TransferType] = this
    @SerialVersionUID(0L)
    case object TRANSFER_DISABLE extends TransferType with TransferType.Recognized {
      val value = 0
      val index = 0
      val name = "TRANSFER_DISABLE"
      override def isTransferDisable: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object TRANSFER_ONCE extends TransferType with TransferType.Recognized {
      val value = 1
      val index = 1
      val name = "TRANSFER_ONCE"
      override def isTransferOnce: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object TRANSFER_REPEATEDLY extends TransferType with TransferType.Recognized {
      val value = 2
      val index = 2
      val name = "TRANSFER_REPEATEDLY"
      override def isTransferRepeatedly: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends TransferType with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(TRANSFER_DISABLE, TRANSFER_ONCE, TRANSFER_REPEATEDLY)
    def fromValue(value: _root_.scala.Int): TransferType = value match {
      case 0 => TRANSFER_DISABLE
      case 1 => TRANSFER_ONCE
      case 2 => TRANSFER_REPEATEDLY
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.Authorize.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.Authorize.scalaDescriptor.enums(0)
  }
  implicit class AuthorizeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Authorize]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.Authorize](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def grant: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.grant)((c_, f_) => c_.copy(grant = f_))
    def granted: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.granted)((c_, f_) => c_.copy(granted = f_))
    def opId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.opId)((c_, f_) => c_.copy(opId = f_))
    def isTransfer: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Authorize.TransferType] = field(_.isTransfer)((c_, f_) => c_.copy(isTransfer = f_))
    def createTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getCreateTime)((c_, f_) => c_.copy(createTime = Option(f_)))
    def optionalCreateTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.createTime)((c_, f_) => c_.copy(createTime = f_))
    def disableTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getDisableTime)((c_, f_) => c_.copy(disableTime = Option(f_)))
    def optionalDisableTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.disableTime)((c_, f_) => c_.copy(disableTime = f_))
    def authorizeValid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.authorizeValid)((c_, f_) => c_.copy(authorizeValid = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val GRANT_FIELD_NUMBER = 2
  final val GRANTED_FIELD_NUMBER = 3
  final val OP_ID_FIELD_NUMBER = 4
  final val IS_TRANSFER_FIELD_NUMBER = 5
  final val CREATE_TIME_FIELD_NUMBER = 6
  final val DISABLE_TIME_FIELD_NUMBER = 7
  final val AUTHORIZE_VALID_FIELD_NUMBER = 8
  final val VERSION_FIELD_NUMBER = 9
  def of(
    id: _root_.scala.Predef.String,
    grant: _root_.scala.Predef.String,
    granted: _root_.scala.Seq[_root_.scala.Predef.String],
    opId: _root_.scala.Seq[_root_.scala.Predef.String],
    isTransfer: rep.proto.rc2.Authorize.TransferType,
    createTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    disableTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    authorizeValid: _root_.scala.Boolean,
    version: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.Authorize = _root_.rep.proto.rc2.Authorize(
    id,
    grant,
    granted,
    opId,
    isTransfer,
    createTime,
    disableTime,
    authorizeValid,
    version,
    unknownFields
  )
}
