// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** @param authorizeId
  *  权限id
  * @param version
  *  默认1.0
  */
@SerialVersionUID(0L)
final case class BindCertToAuthorize(
    authorizeId: _root_.scala.Predef.String = "",
    granted: _root_.scala.Option[rep.proto.rc2.CertId] = _root_.scala.None,
    version: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[BindCertToAuthorize] with scalapb.lenses.Updatable[BindCertToAuthorize] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = authorizeId
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (granted.isDefined) {
        val __value = granted.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = authorizeId
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      granted.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.BindCertToAuthorize = {
      var __authorizeId = this.authorizeId
      var __granted = this.granted
      var __version = this.version
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __authorizeId = _input__.readString()
          case 18 =>
            __granted = Option(_root_.scalapb.LiteParser.readMessage(_input__, __granted.getOrElse(rep.proto.rc2.CertId.defaultInstance)))
          case 26 =>
            __version = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.BindCertToAuthorize(
          authorizeId = __authorizeId,
          granted = __granted,
          version = __version,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withAuthorizeId(__v: _root_.scala.Predef.String): BindCertToAuthorize = copy(authorizeId = __v)
    def getGranted: rep.proto.rc2.CertId = granted.getOrElse(rep.proto.rc2.CertId.defaultInstance)
    def clearGranted: BindCertToAuthorize = copy(granted = _root_.scala.None)
    def withGranted(__v: rep.proto.rc2.CertId): BindCertToAuthorize = copy(granted = Option(__v))
    def withVersion(__v: _root_.scala.Predef.String): BindCertToAuthorize = copy(version = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = authorizeId
          if (__t != "") __t else null
        }
        case 2 => granted.orNull
        case 3 => {
          val __t = version
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(authorizeId)
        case 2 => granted.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => _root_.scalapb.descriptors.PString(version)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.BindCertToAuthorize
}

object BindCertToAuthorize extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.BindCertToAuthorize] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.BindCertToAuthorize] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.BindCertToAuthorize] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.BindCertToAuthorize(
        authorizeId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        granted = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.CertId]]),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = rep.proto.rc2.CertId
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.BindCertToAuthorize(
    authorizeId = "",
    granted = _root_.scala.None,
    version = ""
  )
  implicit class BindCertToAuthorizeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.BindCertToAuthorize]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.BindCertToAuthorize](_l) {
    def authorizeId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.authorizeId)((c_, f_) => c_.copy(authorizeId = f_))
    def granted: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.CertId] = field(_.getGranted)((c_, f_) => c_.copy(granted = Option(f_)))
    def optionalGranted: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[rep.proto.rc2.CertId]] = field(_.granted)((c_, f_) => c_.copy(granted = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
  }
  final val AUTHORIZE_ID_FIELD_NUMBER = 1
  final val GRANTED_FIELD_NUMBER = 2
  final val VERSION_FIELD_NUMBER = 3
  def of(
    authorizeId: _root_.scala.Predef.String,
    granted: _root_.scala.Option[rep.proto.rc2.CertId],
    version: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.BindCertToAuthorize = _root_.rep.proto.rc2.BindCertToAuthorize(
    authorizeId,
    granted,
    version,
    unknownFields
  )
}
