// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

@SerialVersionUID(0L)
final case class BlockchainInfo(
    height: _root_.scala.Long = 0L,
    totalTransactions: _root_.scala.Long = 0L,
    currentBlockHash: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    previousBlockHash: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    currentStateHash: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[BlockchainInfo] with scalapb.lenses.Updatable[BlockchainInfo] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = height
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(1, __value)
        }
      };
      
      {
        val __value = totalTransactions
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(2, __value)
        }
      };
      
      {
        val __value = currentBlockHash
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(3, __value)
        }
      };
      
      {
        val __value = previousBlockHash
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(4, __value)
        }
      };
      
      {
        val __value = currentStateHash
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = height
        if (__v != 0L) {
          _output__.writeUInt64(1, __v)
        }
      };
      {
        val __v = totalTransactions
        if (__v != 0L) {
          _output__.writeUInt64(2, __v)
        }
      };
      {
        val __v = currentBlockHash
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(3, __v)
        }
      };
      {
        val __v = previousBlockHash
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(4, __v)
        }
      };
      {
        val __v = currentStateHash
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.BlockchainInfo = {
      var __height = this.height
      var __totalTransactions = this.totalTransactions
      var __currentBlockHash = this.currentBlockHash
      var __previousBlockHash = this.previousBlockHash
      var __currentStateHash = this.currentStateHash
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __height = _input__.readUInt64()
          case 16 =>
            __totalTransactions = _input__.readUInt64()
          case 26 =>
            __currentBlockHash = _input__.readBytes()
          case 34 =>
            __previousBlockHash = _input__.readBytes()
          case 42 =>
            __currentStateHash = _input__.readBytes()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.BlockchainInfo(
          height = __height,
          totalTransactions = __totalTransactions,
          currentBlockHash = __currentBlockHash,
          previousBlockHash = __previousBlockHash,
          currentStateHash = __currentStateHash,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withHeight(__v: _root_.scala.Long): BlockchainInfo = copy(height = __v)
    def withTotalTransactions(__v: _root_.scala.Long): BlockchainInfo = copy(totalTransactions = __v)
    def withCurrentBlockHash(__v: _root_.com.google.protobuf.ByteString): BlockchainInfo = copy(currentBlockHash = __v)
    def withPreviousBlockHash(__v: _root_.com.google.protobuf.ByteString): BlockchainInfo = copy(previousBlockHash = __v)
    def withCurrentStateHash(__v: _root_.com.google.protobuf.ByteString): BlockchainInfo = copy(currentStateHash = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = height
          if (__t != 0L) __t else null
        }
        case 2 => {
          val __t = totalTransactions
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = currentBlockHash
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 4 => {
          val __t = previousBlockHash
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 5 => {
          val __t = currentStateHash
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(height)
        case 2 => _root_.scalapb.descriptors.PLong(totalTransactions)
        case 3 => _root_.scalapb.descriptors.PByteString(currentBlockHash)
        case 4 => _root_.scalapb.descriptors.PByteString(previousBlockHash)
        case 5 => _root_.scalapb.descriptors.PByteString(currentStateHash)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.BlockchainInfo
}

object BlockchainInfo extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.BlockchainInfo] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.BlockchainInfo] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.BlockchainInfo] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.BlockchainInfo(
        height = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        totalTransactions = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        currentBlockHash = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        previousBlockHash = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        currentStateHash = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(21)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(21)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.BlockchainInfo(
    height = 0L,
    totalTransactions = 0L,
    currentBlockHash = _root_.com.google.protobuf.ByteString.EMPTY,
    previousBlockHash = _root_.com.google.protobuf.ByteString.EMPTY,
    currentStateHash = _root_.com.google.protobuf.ByteString.EMPTY
  )
  implicit class BlockchainInfoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.BlockchainInfo]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.BlockchainInfo](_l) {
    def height: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.height)((c_, f_) => c_.copy(height = f_))
    def totalTransactions: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.totalTransactions)((c_, f_) => c_.copy(totalTransactions = f_))
    def currentBlockHash: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.currentBlockHash)((c_, f_) => c_.copy(currentBlockHash = f_))
    def previousBlockHash: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.previousBlockHash)((c_, f_) => c_.copy(previousBlockHash = f_))
    def currentStateHash: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.currentStateHash)((c_, f_) => c_.copy(currentStateHash = f_))
  }
  final val HEIGHT_FIELD_NUMBER = 1
  final val TOTALTRANSACTIONS_FIELD_NUMBER = 2
  final val CURRENTBLOCKHASH_FIELD_NUMBER = 3
  final val PREVIOUSBLOCKHASH_FIELD_NUMBER = 4
  final val CURRENTSTATEHASH_FIELD_NUMBER = 5
  def of(
    height: _root_.scala.Long,
    totalTransactions: _root_.scala.Long,
    currentBlockHash: _root_.com.google.protobuf.ByteString,
    previousBlockHash: _root_.com.google.protobuf.ByteString,
    currentStateHash: _root_.com.google.protobuf.ByteString,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.BlockchainInfo = _root_.rep.proto.rc2.BlockchainInfo(
    height,
    totalTransactions,
    currentBlockHash,
    previousBlockHash,
    currentStateHash,
    unknownFields
  )
}
