// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** @param version
  *   version - 区块数据版本,以便数据格式升级
  * @param height
  *   区块高度, 从1开始
  * @param commitTx
  *  区块内交易存在性承诺，root value
  * @param commitTxResult
  *   出错交易非成员承诺，由于出错交易也会打入区块，
  *  所以在出具交易存在性证明同时，需要出具该交易不在出错交易集合中的证明
  *  区块内错误交易存在性承诺
  *  bytes commit_tx_err = 4;
  * @param hashPresent
  *  当前区块Hash
  * @param hashPrevious
  *  前一区块Hash
  * @param commitState
  *  状态在区块内的存在性承诺
  * @param commitStateGlobal
  *  全局非过期状态不存在承诺，证明某个状态当前没有更新的值。
  *  将更新的状态复合名（状态名+版本号）写入到该承诺
  * @param heightExpired
  *  过期区块高度
  * @param endorsements
  *  背书签名集合,必须包含出块人签名,不参与hashOfBlock
  */
@SerialVersionUID(0L)
final case class BlockHeader(
    version: _root_.scala.Int = 0,
    height: _root_.scala.Long = 0L,
    commitTx: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    commitTxResult: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    hashPresent: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    hashPrevious: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    commitState: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    commitStateGlobal: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    heightExpired: _root_.scala.Long = 0L,
    endorsements: _root_.scala.Seq[rep.proto.rc2.Signature] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[BlockHeader] with scalapb.lenses.Updatable[BlockHeader] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = version
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      
      {
        val __value = height
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(2, __value)
        }
      };
      
      {
        val __value = commitTx
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(3, __value)
        }
      };
      
      {
        val __value = commitTxResult
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(4, __value)
        }
      };
      
      {
        val __value = hashPresent
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(5, __value)
        }
      };
      
      {
        val __value = hashPrevious
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(6, __value)
        }
      };
      
      {
        val __value = commitState
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(7, __value)
        }
      };
      
      {
        val __value = commitStateGlobal
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(8, __value)
        }
      };
      
      {
        val __value = heightExpired
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(9, __value)
        }
      };
      endorsements.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = version
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      {
        val __v = height
        if (__v != 0L) {
          _output__.writeUInt64(2, __v)
        }
      };
      {
        val __v = commitTx
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(3, __v)
        }
      };
      {
        val __v = commitTxResult
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(4, __v)
        }
      };
      {
        val __v = hashPresent
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(5, __v)
        }
      };
      {
        val __v = hashPrevious
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(6, __v)
        }
      };
      {
        val __v = commitState
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(7, __v)
        }
      };
      {
        val __v = commitStateGlobal
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(8, __v)
        }
      };
      {
        val __v = heightExpired
        if (__v != 0L) {
          _output__.writeUInt64(9, __v)
        }
      };
      endorsements.foreach { __v =>
        val __m = __v
        _output__.writeTag(10, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.BlockHeader = {
      var __version = this.version
      var __height = this.height
      var __commitTx = this.commitTx
      var __commitTxResult = this.commitTxResult
      var __hashPresent = this.hashPresent
      var __hashPrevious = this.hashPrevious
      var __commitState = this.commitState
      var __commitStateGlobal = this.commitStateGlobal
      var __heightExpired = this.heightExpired
      val __endorsements = (_root_.scala.collection.immutable.Vector.newBuilder[rep.proto.rc2.Signature] ++= this.endorsements)
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __version = _input__.readUInt32()
          case 16 =>
            __height = _input__.readUInt64()
          case 26 =>
            __commitTx = _input__.readBytes()
          case 34 =>
            __commitTxResult = _input__.readBytes()
          case 42 =>
            __hashPresent = _input__.readBytes()
          case 50 =>
            __hashPrevious = _input__.readBytes()
          case 58 =>
            __commitState = _input__.readBytes()
          case 66 =>
            __commitStateGlobal = _input__.readBytes()
          case 72 =>
            __heightExpired = _input__.readUInt64()
          case 82 =>
            __endorsements += _root_.scalapb.LiteParser.readMessage(_input__, rep.proto.rc2.Signature.defaultInstance)
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.BlockHeader(
          version = __version,
          height = __height,
          commitTx = __commitTx,
          commitTxResult = __commitTxResult,
          hashPresent = __hashPresent,
          hashPrevious = __hashPrevious,
          commitState = __commitState,
          commitStateGlobal = __commitStateGlobal,
          heightExpired = __heightExpired,
          endorsements = __endorsements.result(),
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withVersion(__v: _root_.scala.Int): BlockHeader = copy(version = __v)
    def withHeight(__v: _root_.scala.Long): BlockHeader = copy(height = __v)
    def withCommitTx(__v: _root_.com.google.protobuf.ByteString): BlockHeader = copy(commitTx = __v)
    def withCommitTxResult(__v: _root_.com.google.protobuf.ByteString): BlockHeader = copy(commitTxResult = __v)
    def withHashPresent(__v: _root_.com.google.protobuf.ByteString): BlockHeader = copy(hashPresent = __v)
    def withHashPrevious(__v: _root_.com.google.protobuf.ByteString): BlockHeader = copy(hashPrevious = __v)
    def withCommitState(__v: _root_.com.google.protobuf.ByteString): BlockHeader = copy(commitState = __v)
    def withCommitStateGlobal(__v: _root_.com.google.protobuf.ByteString): BlockHeader = copy(commitStateGlobal = __v)
    def withHeightExpired(__v: _root_.scala.Long): BlockHeader = copy(heightExpired = __v)
    def clearEndorsements = copy(endorsements = _root_.scala.Seq.empty)
    def addEndorsements(__vs: rep.proto.rc2.Signature*): BlockHeader = addAllEndorsements(__vs)
    def addAllEndorsements(__vs: Iterable[rep.proto.rc2.Signature]): BlockHeader = copy(endorsements = endorsements ++ __vs)
    def withEndorsements(__v: _root_.scala.Seq[rep.proto.rc2.Signature]): BlockHeader = copy(endorsements = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = version
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = height
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = commitTx
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 4 => {
          val __t = commitTxResult
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 5 => {
          val __t = hashPresent
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 6 => {
          val __t = hashPrevious
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 7 => {
          val __t = commitState
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 8 => {
          val __t = commitStateGlobal
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 9 => {
          val __t = heightExpired
          if (__t != 0L) __t else null
        }
        case 10 => endorsements
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(version)
        case 2 => _root_.scalapb.descriptors.PLong(height)
        case 3 => _root_.scalapb.descriptors.PByteString(commitTx)
        case 4 => _root_.scalapb.descriptors.PByteString(commitTxResult)
        case 5 => _root_.scalapb.descriptors.PByteString(hashPresent)
        case 6 => _root_.scalapb.descriptors.PByteString(hashPrevious)
        case 7 => _root_.scalapb.descriptors.PByteString(commitState)
        case 8 => _root_.scalapb.descriptors.PByteString(commitStateGlobal)
        case 9 => _root_.scalapb.descriptors.PLong(heightExpired)
        case 10 => _root_.scalapb.descriptors.PRepeated(endorsements.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.BlockHeader
}

object BlockHeader extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.BlockHeader] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.BlockHeader] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.BlockHeader] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.BlockHeader(
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        height = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        commitTx = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        commitTxResult = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        hashPresent = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        hashPrevious = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        commitState = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        commitStateGlobal = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        heightExpired = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        endorsements = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).map(_.as[_root_.scala.Seq[rep.proto.rc2.Signature]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(14)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(14)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 10 => __out = rep.proto.rc2.Signature
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.BlockHeader(
    version = 0,
    height = 0L,
    commitTx = _root_.com.google.protobuf.ByteString.EMPTY,
    commitTxResult = _root_.com.google.protobuf.ByteString.EMPTY,
    hashPresent = _root_.com.google.protobuf.ByteString.EMPTY,
    hashPrevious = _root_.com.google.protobuf.ByteString.EMPTY,
    commitState = _root_.com.google.protobuf.ByteString.EMPTY,
    commitStateGlobal = _root_.com.google.protobuf.ByteString.EMPTY,
    heightExpired = 0L,
    endorsements = _root_.scala.Seq.empty
  )
  implicit class BlockHeaderLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.BlockHeader]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.BlockHeader](_l) {
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.version)((c_, f_) => c_.copy(version = f_))
    def height: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.height)((c_, f_) => c_.copy(height = f_))
    def commitTx: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.commitTx)((c_, f_) => c_.copy(commitTx = f_))
    def commitTxResult: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.commitTxResult)((c_, f_) => c_.copy(commitTxResult = f_))
    def hashPresent: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.hashPresent)((c_, f_) => c_.copy(hashPresent = f_))
    def hashPrevious: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.hashPrevious)((c_, f_) => c_.copy(hashPrevious = f_))
    def commitState: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.commitState)((c_, f_) => c_.copy(commitState = f_))
    def commitStateGlobal: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.commitStateGlobal)((c_, f_) => c_.copy(commitStateGlobal = f_))
    def heightExpired: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.heightExpired)((c_, f_) => c_.copy(heightExpired = f_))
    def endorsements: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[rep.proto.rc2.Signature]] = field(_.endorsements)((c_, f_) => c_.copy(endorsements = f_))
  }
  final val VERSION_FIELD_NUMBER = 1
  final val HEIGHT_FIELD_NUMBER = 2
  final val COMMIT_TX_FIELD_NUMBER = 3
  final val COMMIT_TX_RESULT_FIELD_NUMBER = 4
  final val HASH_PRESENT_FIELD_NUMBER = 5
  final val HASH_PREVIOUS_FIELD_NUMBER = 6
  final val COMMIT_STATE_FIELD_NUMBER = 7
  final val COMMIT_STATE_GLOBAL_FIELD_NUMBER = 8
  final val HEIGHT_EXPIRED_FIELD_NUMBER = 9
  final val ENDORSEMENTS_FIELD_NUMBER = 10
  def of(
    version: _root_.scala.Int,
    height: _root_.scala.Long,
    commitTx: _root_.com.google.protobuf.ByteString,
    commitTxResult: _root_.com.google.protobuf.ByteString,
    hashPresent: _root_.com.google.protobuf.ByteString,
    hashPrevious: _root_.com.google.protobuf.ByteString,
    commitState: _root_.com.google.protobuf.ByteString,
    commitStateGlobal: _root_.com.google.protobuf.ByteString,
    heightExpired: _root_.scala.Long,
    endorsements: _root_.scala.Seq[rep.proto.rc2.Signature],
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.BlockHeader = _root_.rep.proto.rc2.BlockHeader(
    version,
    height,
    commitTx,
    commitTxResult,
    hashPresent,
    hashPrevious,
    commitState,
    commitStateGlobal,
    heightExpired,
    endorsements,
    unknownFields
  )
}
