// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 账户证书标示
  *
  * @param certificate
  *  内含签发机构
  * @param algType
  *  直接填写具体算法，如:ECDSA下的SHA1withECDSA,SHA512withECDSA等
  * @param certValid
  *  证书是否有效，true 有效；false 无效；protobuf默认该值为false
  * @param regTime
  *  注册时间
  * @param unregTime
  *  注销时间
  * @param certType
  *  1=普通证书，2=身份验证证书，
  * @param id
  *  证书名称
  * @param certHash
  *  证书的SHA256
  * @param version
  *  默认1.0
  */
@SerialVersionUID(0L)
final case class Certificate(
    certificate: _root_.scala.Predef.String = "",
    algType: _root_.scala.Predef.String = "",
    certValid: _root_.scala.Boolean = false,
    regTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    unregTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    certType: rep.proto.rc2.Certificate.CertType = rep.proto.rc2.Certificate.CertType.CERT_UNDEFINED,
    id: _root_.scala.Option[rep.proto.rc2.CertId] = _root_.scala.None,
    certHash: _root_.scala.Predef.String = "",
    version: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Certificate] with scalapb.lenses.Updatable[Certificate] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = certificate
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = algType
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = certValid
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      if (regTime.isDefined) {
        val __value = regTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (unregTime.isDefined) {
        val __value = unregTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = certType
        if (__value != rep.proto.rc2.Certificate.CertType.CERT_UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(6, __value.value)
        }
      };
      if (id.isDefined) {
        val __value = id.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = certHash
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = certificate
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = algType
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = certValid
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      regTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unregTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = certType
        if (__v != rep.proto.rc2.Certificate.CertType.CERT_UNDEFINED) {
          _output__.writeEnum(6, __v.value)
        }
      };
      id.foreach { __v =>
        val __m = __v
        _output__.writeTag(7, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = certHash
        if (__v != "") {
          _output__.writeString(8, __v)
        }
      };
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(9, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.Certificate = {
      var __certificate = this.certificate
      var __algType = this.algType
      var __certValid = this.certValid
      var __regTime = this.regTime
      var __unregTime = this.unregTime
      var __certType = this.certType
      var __id = this.id
      var __certHash = this.certHash
      var __version = this.version
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __certificate = _input__.readString()
          case 18 =>
            __algType = _input__.readString()
          case 24 =>
            __certValid = _input__.readBool()
          case 34 =>
            __regTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __regTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 42 =>
            __unregTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __unregTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 48 =>
            __certType = rep.proto.rc2.Certificate.CertType.fromValue(_input__.readEnum())
          case 58 =>
            __id = Option(_root_.scalapb.LiteParser.readMessage(_input__, __id.getOrElse(rep.proto.rc2.CertId.defaultInstance)))
          case 66 =>
            __certHash = _input__.readString()
          case 74 =>
            __version = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.Certificate(
          certificate = __certificate,
          algType = __algType,
          certValid = __certValid,
          regTime = __regTime,
          unregTime = __unregTime,
          certType = __certType,
          id = __id,
          certHash = __certHash,
          version = __version,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withCertificate(__v: _root_.scala.Predef.String): Certificate = copy(certificate = __v)
    def withAlgType(__v: _root_.scala.Predef.String): Certificate = copy(algType = __v)
    def withCertValid(__v: _root_.scala.Boolean): Certificate = copy(certValid = __v)
    def getRegTime: com.google.protobuf.timestamp.Timestamp = regTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearRegTime: Certificate = copy(regTime = _root_.scala.None)
    def withRegTime(__v: com.google.protobuf.timestamp.Timestamp): Certificate = copy(regTime = Option(__v))
    def getUnregTime: com.google.protobuf.timestamp.Timestamp = unregTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearUnregTime: Certificate = copy(unregTime = _root_.scala.None)
    def withUnregTime(__v: com.google.protobuf.timestamp.Timestamp): Certificate = copy(unregTime = Option(__v))
    def withCertType(__v: rep.proto.rc2.Certificate.CertType): Certificate = copy(certType = __v)
    def getId: rep.proto.rc2.CertId = id.getOrElse(rep.proto.rc2.CertId.defaultInstance)
    def clearId: Certificate = copy(id = _root_.scala.None)
    def withId(__v: rep.proto.rc2.CertId): Certificate = copy(id = Option(__v))
    def withCertHash(__v: _root_.scala.Predef.String): Certificate = copy(certHash = __v)
    def withVersion(__v: _root_.scala.Predef.String): Certificate = copy(version = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = certificate
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = algType
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = certValid
          if (__t != false) __t else null
        }
        case 4 => regTime.orNull
        case 5 => unregTime.orNull
        case 6 => {
          val __t = certType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 7 => id.orNull
        case 8 => {
          val __t = certHash
          if (__t != "") __t else null
        }
        case 9 => {
          val __t = version
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(certificate)
        case 2 => _root_.scalapb.descriptors.PString(algType)
        case 3 => _root_.scalapb.descriptors.PBoolean(certValid)
        case 4 => regTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 5 => unregTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 6 => _root_.scalapb.descriptors.PEnum(certType.scalaValueDescriptor)
        case 7 => id.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 8 => _root_.scalapb.descriptors.PString(certHash)
        case 9 => _root_.scalapb.descriptors.PString(version)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.Certificate
}

object Certificate extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.Certificate] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.Certificate] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.Certificate] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.Certificate(
        certificate = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        algType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        certValid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        regTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        unregTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        certType = rep.proto.rc2.Certificate.CertType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.Certificate.CertType.CERT_UNDEFINED.scalaValueDescriptor).number),
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.CertId]]),
        certHash = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = com.google.protobuf.timestamp.Timestamp
      case 5 => __out = com.google.protobuf.timestamp.Timestamp
      case 7 => __out = rep.proto.rc2.CertId
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 6 => rep.proto.rc2.Certificate.CertType
    }
  }
  lazy val defaultInstance = rep.proto.rc2.Certificate(
    certificate = "",
    algType = "",
    certValid = false,
    regTime = _root_.scala.None,
    unregTime = _root_.scala.None,
    certType = rep.proto.rc2.Certificate.CertType.CERT_UNDEFINED,
    id = _root_.scala.None,
    certHash = "",
    version = ""
  )
  sealed trait CertType extends _root_.scalapb.GeneratedEnum {
    type EnumType = CertType
    def isCertUndefined: _root_.scala.Boolean = false
    def isCertAuthentication: _root_.scala.Boolean = false
    def isCertCustom: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[CertType] = rep.proto.rc2.Certificate.CertType
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.Certificate.CertType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.Certificate.CertType.Recognized])
  }
  
  object CertType extends _root_.scalapb.GeneratedEnumCompanion[CertType] {
    sealed trait Recognized extends CertType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[CertType] = this
    @SerialVersionUID(0L)
    case object CERT_UNDEFINED extends CertType with CertType.Recognized {
      val value = 0
      val index = 0
      val name = "CERT_UNDEFINED"
      override def isCertUndefined: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CERT_AUTHENTICATION extends CertType with CertType.Recognized {
      val value = 1
      val index = 1
      val name = "CERT_AUTHENTICATION"
      override def isCertAuthentication: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CERT_CUSTOM extends CertType with CertType.Recognized {
      val value = 2
      val index = 2
      val name = "CERT_CUSTOM"
      override def isCertCustom: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends CertType with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(CERT_UNDEFINED, CERT_AUTHENTICATION, CERT_CUSTOM)
    def fromValue(value: _root_.scala.Int): CertType = value match {
      case 0 => CERT_UNDEFINED
      case 1 => CERT_AUTHENTICATION
      case 2 => CERT_CUSTOM
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.Certificate.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.Certificate.scalaDescriptor.enums(0)
  }
  implicit class CertificateLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Certificate]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.Certificate](_l) {
    def certificate: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.certificate)((c_, f_) => c_.copy(certificate = f_))
    def algType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.algType)((c_, f_) => c_.copy(algType = f_))
    def certValid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.certValid)((c_, f_) => c_.copy(certValid = f_))
    def regTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getRegTime)((c_, f_) => c_.copy(regTime = Option(f_)))
    def optionalRegTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.regTime)((c_, f_) => c_.copy(regTime = f_))
    def unregTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getUnregTime)((c_, f_) => c_.copy(unregTime = Option(f_)))
    def optionalUnregTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.unregTime)((c_, f_) => c_.copy(unregTime = f_))
    def certType: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Certificate.CertType] = field(_.certType)((c_, f_) => c_.copy(certType = f_))
    def id: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.CertId] = field(_.getId)((c_, f_) => c_.copy(id = Option(f_)))
    def optionalId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[rep.proto.rc2.CertId]] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def certHash: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.certHash)((c_, f_) => c_.copy(certHash = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
  }
  final val CERTIFICATE_FIELD_NUMBER = 1
  final val ALG_TYPE_FIELD_NUMBER = 2
  final val CERT_VALID_FIELD_NUMBER = 3
  final val REG_TIME_FIELD_NUMBER = 4
  final val UNREG_TIME_FIELD_NUMBER = 5
  final val CERT_TYPE_FIELD_NUMBER = 6
  final val ID_FIELD_NUMBER = 7
  final val CERT_HASH_FIELD_NUMBER = 8
  final val VERSION_FIELD_NUMBER = 9
  def of(
    certificate: _root_.scala.Predef.String,
    algType: _root_.scala.Predef.String,
    certValid: _root_.scala.Boolean,
    regTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    unregTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    certType: rep.proto.rc2.Certificate.CertType,
    id: _root_.scala.Option[rep.proto.rc2.CertId],
    certHash: _root_.scala.Predef.String,
    version: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.Certificate = _root_.rep.proto.rc2.Certificate(
    certificate,
    algType,
    certValid,
    regTime,
    unregTime,
    certType,
    id,
    certHash,
    version,
    unknownFields
  )
}
