// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 账户证书标示
  *
  * @param creditCode
  *  社会信用代码（个人或机构）或者DID，推荐使用DID
  * @param certName
  *  当前用户注册证书的名称
  * @param version
  *  默认1.0
  */
@SerialVersionUID(0L)
final case class CertId(
    creditCode: _root_.scala.Predef.String = "",
    certName: _root_.scala.Predef.String = "",
    version: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[CertId] with scalapb.lenses.Updatable[CertId] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = creditCode
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = certName
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = creditCode
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = certName
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.CertId = {
      var __creditCode = this.creditCode
      var __certName = this.certName
      var __version = this.version
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __creditCode = _input__.readString()
          case 18 =>
            __certName = _input__.readString()
          case 26 =>
            __version = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.CertId(
          creditCode = __creditCode,
          certName = __certName,
          version = __version,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withCreditCode(__v: _root_.scala.Predef.String): CertId = copy(creditCode = __v)
    def withCertName(__v: _root_.scala.Predef.String): CertId = copy(certName = __v)
    def withVersion(__v: _root_.scala.Predef.String): CertId = copy(version = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = creditCode
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = certName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = version
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(creditCode)
        case 2 => _root_.scalapb.descriptors.PString(certName)
        case 3 => _root_.scalapb.descriptors.PString(version)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.CertId
}

object CertId extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.CertId] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.CertId] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.CertId] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.CertId(
        creditCode = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        certName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.CertId(
    creditCode = "",
    certName = "",
    version = ""
  )
  implicit class CertIdLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.CertId]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.CertId](_l) {
    def creditCode: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.creditCode)((c_, f_) => c_.copy(creditCode = f_))
    def certName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.certName)((c_, f_) => c_.copy(certName = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
  }
  final val CREDIT_CODE_FIELD_NUMBER = 1
  final val CERT_NAME_FIELD_NUMBER = 2
  final val VERSION_FIELD_NUMBER = 3
  def of(
    creditCode: _root_.scala.Predef.String,
    certName: _root_.scala.Predef.String,
    version: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.CertId = _root_.rep.proto.rc2.CertId(
    creditCode,
    certName,
    version,
    unknownFields
  )
}
