// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 合约方法调用及实际参数
  */
@SerialVersionUID(0L)
final case class ChaincodeInput(
    function: _root_.scala.Predef.String = "",
    args: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[ChaincodeInput] with scalapb.lenses.Updatable[ChaincodeInput] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = function
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      args.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = function
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      args.foreach { __v =>
        val __m = __v
        _output__.writeString(2, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.ChaincodeInput = {
      var __function = this.function
      val __args = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.args)
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __function = _input__.readString()
          case 18 =>
            __args += _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.ChaincodeInput(
          function = __function,
          args = __args.result(),
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withFunction(__v: _root_.scala.Predef.String): ChaincodeInput = copy(function = __v)
    def clearArgs = copy(args = _root_.scala.Seq.empty)
    def addArgs(__vs: _root_.scala.Predef.String*): ChaincodeInput = addAllArgs(__vs)
    def addAllArgs(__vs: Iterable[_root_.scala.Predef.String]): ChaincodeInput = copy(args = args ++ __vs)
    def withArgs(__v: _root_.scala.Seq[_root_.scala.Predef.String]): ChaincodeInput = copy(args = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = function
          if (__t != "") __t else null
        }
        case 2 => args
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(function)
        case 2 => _root_.scalapb.descriptors.PRepeated(args.iterator.map(_root_.scalapb.descriptors.PString).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.ChaincodeInput
}

object ChaincodeInput extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.ChaincodeInput] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.ChaincodeInput] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.ChaincodeInput] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.ChaincodeInput(
        function = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        args = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(11)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(11)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.ChaincodeInput(
    function = "",
    args = _root_.scala.Seq.empty
  )
  implicit class ChaincodeInputLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeInput]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.ChaincodeInput](_l) {
    def function: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.function)((c_, f_) => c_.copy(function = f_))
    def args: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.args)((c_, f_) => c_.copy(args = f_))
  }
  final val FUNCTION_FIELD_NUMBER = 1
  final val ARGS_FIELD_NUMBER = 2
  def of(
    function: _root_.scala.Predef.String,
    args: _root_.scala.Seq[_root_.scala.Predef.String],
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.ChaincodeInput = _root_.rep.proto.rc2.ChaincodeInput(
    function,
    args,
    unknownFields
  )
}
