// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 合约定义,部署/升级
  *
  * @param timeout
  *  部署超时
  * @param codePackage
  *  完整的代码内容
  * @param legalProse
  *  合约规则的法律描述文本
  * @param isCalledByOtherContracts
  *  true 本合约可以被其他合约调用；false 不可以被其他合约调用。默认值是false
  */
@SerialVersionUID(0L)
final case class ChaincodeDeploy(
    timeout: _root_.scala.Int = 0,
    codePackage: _root_.scala.Predef.String = "",
    legalProse: _root_.scala.Predef.String = "",
    cType: rep.proto.rc2.ChaincodeDeploy.CodeType = rep.proto.rc2.ChaincodeDeploy.CodeType.CODE_UNDEFINED,
    rType: rep.proto.rc2.ChaincodeDeploy.RunType = rep.proto.rc2.ChaincodeDeploy.RunType.RUN_UNDEFINED,
    sType: rep.proto.rc2.ChaincodeDeploy.StateType = rep.proto.rc2.ChaincodeDeploy.StateType.STATE_UNDEFINED,
    initParameter: _root_.scala.Predef.String = "",
    cclassification: rep.proto.rc2.ChaincodeDeploy.ContractClassification = rep.proto.rc2.ChaincodeDeploy.ContractClassification.CONTRACT_UNDEFINED,
    isCalledByOtherContracts: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[ChaincodeDeploy] with scalapb.lenses.Updatable[ChaincodeDeploy] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = timeout
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(1, __value)
        }
      };
      
      {
        val __value = codePackage
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = legalProse
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = cType
        if (__value != rep.proto.rc2.ChaincodeDeploy.CodeType.CODE_UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(4, __value.value)
        }
      };
      
      {
        val __value = rType
        if (__value != rep.proto.rc2.ChaincodeDeploy.RunType.RUN_UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value.value)
        }
      };
      
      {
        val __value = sType
        if (__value != rep.proto.rc2.ChaincodeDeploy.StateType.STATE_UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(6, __value.value)
        }
      };
      
      {
        val __value = initParameter
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      
      {
        val __value = cclassification
        if (__value != rep.proto.rc2.ChaincodeDeploy.ContractClassification.CONTRACT_UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(8, __value.value)
        }
      };
      
      {
        val __value = isCalledByOtherContracts
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(9, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = timeout
        if (__v != 0) {
          _output__.writeInt32(1, __v)
        }
      };
      {
        val __v = codePackage
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = legalProse
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = cType
        if (__v != rep.proto.rc2.ChaincodeDeploy.CodeType.CODE_UNDEFINED) {
          _output__.writeEnum(4, __v.value)
        }
      };
      {
        val __v = rType
        if (__v != rep.proto.rc2.ChaincodeDeploy.RunType.RUN_UNDEFINED) {
          _output__.writeEnum(5, __v.value)
        }
      };
      {
        val __v = sType
        if (__v != rep.proto.rc2.ChaincodeDeploy.StateType.STATE_UNDEFINED) {
          _output__.writeEnum(6, __v.value)
        }
      };
      {
        val __v = initParameter
        if (__v != "") {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = cclassification
        if (__v != rep.proto.rc2.ChaincodeDeploy.ContractClassification.CONTRACT_UNDEFINED) {
          _output__.writeEnum(8, __v.value)
        }
      };
      {
        val __v = isCalledByOtherContracts
        if (__v != false) {
          _output__.writeBool(9, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.ChaincodeDeploy = {
      var __timeout = this.timeout
      var __codePackage = this.codePackage
      var __legalProse = this.legalProse
      var __cType = this.cType
      var __rType = this.rType
      var __sType = this.sType
      var __initParameter = this.initParameter
      var __cclassification = this.cclassification
      var __isCalledByOtherContracts = this.isCalledByOtherContracts
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __timeout = _input__.readInt32()
          case 18 =>
            __codePackage = _input__.readString()
          case 26 =>
            __legalProse = _input__.readString()
          case 32 =>
            __cType = rep.proto.rc2.ChaincodeDeploy.CodeType.fromValue(_input__.readEnum())
          case 40 =>
            __rType = rep.proto.rc2.ChaincodeDeploy.RunType.fromValue(_input__.readEnum())
          case 48 =>
            __sType = rep.proto.rc2.ChaincodeDeploy.StateType.fromValue(_input__.readEnum())
          case 58 =>
            __initParameter = _input__.readString()
          case 64 =>
            __cclassification = rep.proto.rc2.ChaincodeDeploy.ContractClassification.fromValue(_input__.readEnum())
          case 72 =>
            __isCalledByOtherContracts = _input__.readBool()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.ChaincodeDeploy(
          timeout = __timeout,
          codePackage = __codePackage,
          legalProse = __legalProse,
          cType = __cType,
          rType = __rType,
          sType = __sType,
          initParameter = __initParameter,
          cclassification = __cclassification,
          isCalledByOtherContracts = __isCalledByOtherContracts,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withTimeout(__v: _root_.scala.Int): ChaincodeDeploy = copy(timeout = __v)
    def withCodePackage(__v: _root_.scala.Predef.String): ChaincodeDeploy = copy(codePackage = __v)
    def withLegalProse(__v: _root_.scala.Predef.String): ChaincodeDeploy = copy(legalProse = __v)
    def withCType(__v: rep.proto.rc2.ChaincodeDeploy.CodeType): ChaincodeDeploy = copy(cType = __v)
    def withRType(__v: rep.proto.rc2.ChaincodeDeploy.RunType): ChaincodeDeploy = copy(rType = __v)
    def withSType(__v: rep.proto.rc2.ChaincodeDeploy.StateType): ChaincodeDeploy = copy(sType = __v)
    def withInitParameter(__v: _root_.scala.Predef.String): ChaincodeDeploy = copy(initParameter = __v)
    def withCclassification(__v: rep.proto.rc2.ChaincodeDeploy.ContractClassification): ChaincodeDeploy = copy(cclassification = __v)
    def withIsCalledByOtherContracts(__v: _root_.scala.Boolean): ChaincodeDeploy = copy(isCalledByOtherContracts = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = timeout
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = codePackage
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = legalProse
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = cType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 5 => {
          val __t = rType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 6 => {
          val __t = sType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 7 => {
          val __t = initParameter
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = cclassification.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 9 => {
          val __t = isCalledByOtherContracts
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(timeout)
        case 2 => _root_.scalapb.descriptors.PString(codePackage)
        case 3 => _root_.scalapb.descriptors.PString(legalProse)
        case 4 => _root_.scalapb.descriptors.PEnum(cType.scalaValueDescriptor)
        case 5 => _root_.scalapb.descriptors.PEnum(rType.scalaValueDescriptor)
        case 6 => _root_.scalapb.descriptors.PEnum(sType.scalaValueDescriptor)
        case 7 => _root_.scalapb.descriptors.PString(initParameter)
        case 8 => _root_.scalapb.descriptors.PEnum(cclassification.scalaValueDescriptor)
        case 9 => _root_.scalapb.descriptors.PBoolean(isCalledByOtherContracts)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.ChaincodeDeploy
}

object ChaincodeDeploy extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.ChaincodeDeploy] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.ChaincodeDeploy] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.ChaincodeDeploy] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.ChaincodeDeploy(
        timeout = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        codePackage = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        legalProse = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        cType = rep.proto.rc2.ChaincodeDeploy.CodeType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.ChaincodeDeploy.CodeType.CODE_UNDEFINED.scalaValueDescriptor).number),
        rType = rep.proto.rc2.ChaincodeDeploy.RunType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.ChaincodeDeploy.RunType.RUN_UNDEFINED.scalaValueDescriptor).number),
        sType = rep.proto.rc2.ChaincodeDeploy.StateType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.ChaincodeDeploy.StateType.STATE_UNDEFINED.scalaValueDescriptor).number),
        initParameter = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        cclassification = rep.proto.rc2.ChaincodeDeploy.ContractClassification.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.ChaincodeDeploy.ContractClassification.CONTRACT_UNDEFINED.scalaValueDescriptor).number),
        isCalledByOtherContracts = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(18)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(18)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 4 => rep.proto.rc2.ChaincodeDeploy.CodeType
      case 5 => rep.proto.rc2.ChaincodeDeploy.RunType
      case 6 => rep.proto.rc2.ChaincodeDeploy.StateType
      case 8 => rep.proto.rc2.ChaincodeDeploy.ContractClassification
    }
  }
  lazy val defaultInstance = rep.proto.rc2.ChaincodeDeploy(
    timeout = 0,
    codePackage = "",
    legalProse = "",
    cType = rep.proto.rc2.ChaincodeDeploy.CodeType.CODE_UNDEFINED,
    rType = rep.proto.rc2.ChaincodeDeploy.RunType.RUN_UNDEFINED,
    sType = rep.proto.rc2.ChaincodeDeploy.StateType.STATE_UNDEFINED,
    initParameter = "",
    cclassification = rep.proto.rc2.ChaincodeDeploy.ContractClassification.CONTRACT_UNDEFINED,
    isCalledByOtherContracts = false
  )
  /** 合约类型
    */
  sealed trait CodeType extends _root_.scalapb.GeneratedEnum {
    type EnumType = CodeType
    def isCodeUndefined: _root_.scala.Boolean = false
    def isCodeJavascript: _root_.scala.Boolean = false
    def isCodeScala: _root_.scala.Boolean = false
    def isCodeVclDll: _root_.scala.Boolean = false
    def isCodeVclExe: _root_.scala.Boolean = false
    def isCodeVclWasm: _root_.scala.Boolean = false
    def isCodeWasm: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[CodeType] = rep.proto.rc2.ChaincodeDeploy.CodeType
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.ChaincodeDeploy.CodeType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.ChaincodeDeploy.CodeType.Recognized])
  }
  
  object CodeType extends _root_.scalapb.GeneratedEnumCompanion[CodeType] {
    sealed trait Recognized extends CodeType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[CodeType] = this
    @SerialVersionUID(0L)
    case object CODE_UNDEFINED extends CodeType with CodeType.Recognized {
      val value = 0
      val index = 0
      val name = "CODE_UNDEFINED"
      override def isCodeUndefined: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CODE_JAVASCRIPT extends CodeType with CodeType.Recognized {
      val value = 1
      val index = 1
      val name = "CODE_JAVASCRIPT"
      override def isCodeJavascript: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CODE_SCALA extends CodeType with CodeType.Recognized {
      val value = 2
      val index = 2
      val name = "CODE_SCALA"
      override def isCodeScala: _root_.scala.Boolean = true
    }
    
    /** 合约多语言：vcl合约
      * VCL 以动态库加载执行
      */
    @SerialVersionUID(0L)
    case object CODE_VCL_DLL extends CodeType with CodeType.Recognized {
      val value = 3
      val index = 3
      val name = "CODE_VCL_DLL"
      override def isCodeVclDll: _root_.scala.Boolean = true
    }
    
    /** VCL 以可执行代码加载执行
      */
    @SerialVersionUID(0L)
    case object CODE_VCL_EXE extends CodeType with CodeType.Recognized {
      val value = 4
      val index = 4
      val name = "CODE_VCL_EXE"
      override def isCodeVclExe: _root_.scala.Boolean = true
    }
    
    /** VCL 以WASM加载执行
      */
    @SerialVersionUID(0L)
    case object CODE_VCL_WASM extends CodeType with CodeType.Recognized {
      val value = 5
      val index = 5
      val name = "CODE_VCL_WASM"
      override def isCodeVclWasm: _root_.scala.Boolean = true
    }
    
    /** WASM字节码合约
      */
    @SerialVersionUID(0L)
    case object CODE_WASM extends CodeType with CodeType.Recognized {
      val value = 6
      val index = 6
      val name = "CODE_WASM"
      override def isCodeWasm: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends CodeType with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(CODE_UNDEFINED, CODE_JAVASCRIPT, CODE_SCALA, CODE_VCL_DLL, CODE_VCL_EXE, CODE_VCL_WASM, CODE_WASM)
    def fromValue(value: _root_.scala.Int): CodeType = value match {
      case 0 => CODE_UNDEFINED
      case 1 => CODE_JAVASCRIPT
      case 2 => CODE_SCALA
      case 3 => CODE_VCL_DLL
      case 4 => CODE_VCL_EXE
      case 5 => CODE_VCL_WASM
      case 6 => CODE_WASM
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.scalaDescriptor.enums(0)
  }
  /** 指定串行并行执行
    */
  sealed trait RunType extends _root_.scalapb.GeneratedEnum {
    type EnumType = RunType
    def isRunUndefined: _root_.scala.Boolean = false
    def isRunSerial: _root_.scala.Boolean = false
    def isRunParallel: _root_.scala.Boolean = false
    def isRunOptional: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[RunType] = rep.proto.rc2.ChaincodeDeploy.RunType
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.ChaincodeDeploy.RunType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.ChaincodeDeploy.RunType.Recognized])
  }
  
  object RunType extends _root_.scalapb.GeneratedEnumCompanion[RunType] {
    sealed trait Recognized extends RunType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[RunType] = this
    @SerialVersionUID(0L)
    case object RUN_UNDEFINED extends RunType with RunType.Recognized {
      val value = 0
      val index = 0
      val name = "RUN_UNDEFINED"
      override def isRunUndefined: _root_.scala.Boolean = true
    }
    
    /** 指定串行执行
      */
    @SerialVersionUID(0L)
    case object RUN_SERIAL extends RunType with RunType.Recognized {
      val value = 1
      val index = 1
      val name = "RUN_SERIAL"
      override def isRunSerial: _root_.scala.Boolean = true
    }
    
    /** 指定并行执行
      */
    @SerialVersionUID(0L)
    case object RUN_PARALLEL extends RunType with RunType.Recognized {
      val value = 2
      val index = 2
      val name = "RUN_PARALLEL"
      override def isRunParallel: _root_.scala.Boolean = true
    }
    
    /** 由调度模块决定
      */
    @SerialVersionUID(0L)
    case object RUN_OPTIONAL extends RunType with RunType.Recognized {
      val value = 3
      val index = 3
      val name = "RUN_OPTIONAL"
      override def isRunOptional: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends RunType with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(RUN_UNDEFINED, RUN_SERIAL, RUN_PARALLEL, RUN_OPTIONAL)
    def fromValue(value: _root_.scala.Int): RunType = value match {
      case 0 => RUN_UNDEFINED
      case 1 => RUN_SERIAL
      case 2 => RUN_PARALLEL
      case 3 => RUN_OPTIONAL
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.javaDescriptor.getEnumTypes.get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.scalaDescriptor.enums(1)
  }
  /** 轻节点证明：合约可决定是否需要在全局状态中维护存在性证明
    * 例如:存证类合约，由于状态值不会反复修改，无需全局存在性证明
    */
  sealed trait StateType extends _root_.scalapb.GeneratedEnum {
    type EnumType = StateType
    def isStateUndefined: _root_.scala.Boolean = false
    def isStateBlock: _root_.scala.Boolean = false
    def isStateGlobal: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[StateType] = rep.proto.rc2.ChaincodeDeploy.StateType
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.ChaincodeDeploy.StateType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.ChaincodeDeploy.StateType.Recognized])
  }
  
  object StateType extends _root_.scalapb.GeneratedEnumCompanion[StateType] {
    sealed trait Recognized extends StateType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[StateType] = this
    @SerialVersionUID(0L)
    case object STATE_UNDEFINED extends StateType with StateType.Recognized {
      val value = 0
      val index = 0
      val name = "STATE_UNDEFINED"
      override def isStateUndefined: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object STATE_BLOCK extends StateType with StateType.Recognized {
      val value = 1
      val index = 1
      val name = "STATE_BLOCK"
      override def isStateBlock: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object STATE_GLOBAL extends StateType with StateType.Recognized {
      val value = 2
      val index = 2
      val name = "STATE_GLOBAL"
      override def isStateGlobal: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends StateType with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(STATE_UNDEFINED, STATE_BLOCK, STATE_GLOBAL)
    def fromValue(value: _root_.scala.Int): StateType = value match {
      case 0 => STATE_UNDEFINED
      case 1 => STATE_BLOCK
      case 2 => STATE_GLOBAL
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.javaDescriptor.getEnumTypes.get(2)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.scalaDescriptor.enums(2)
  }
  /** 合约分级 系统合约 用户合约
    */
  sealed trait ContractClassification extends _root_.scalapb.GeneratedEnum {
    type EnumType = ContractClassification
    def isContractUndefined: _root_.scala.Boolean = false
    def isContractSystem: _root_.scala.Boolean = false
    def isContractCustom: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[ContractClassification] = rep.proto.rc2.ChaincodeDeploy.ContractClassification
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.ChaincodeDeploy.ContractClassification.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.ChaincodeDeploy.ContractClassification.Recognized])
  }
  
  object ContractClassification extends _root_.scalapb.GeneratedEnumCompanion[ContractClassification] {
    sealed trait Recognized extends ContractClassification
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ContractClassification] = this
    @SerialVersionUID(0L)
    case object CONTRACT_UNDEFINED extends ContractClassification with ContractClassification.Recognized {
      val value = 0
      val index = 0
      val name = "CONTRACT_UNDEFINED"
      override def isContractUndefined: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CONTRACT_SYSTEM extends ContractClassification with ContractClassification.Recognized {
      val value = 1
      val index = 1
      val name = "CONTRACT_SYSTEM"
      override def isContractSystem: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CONTRACT_CUSTOM extends ContractClassification with ContractClassification.Recognized {
      val value = 2
      val index = 2
      val name = "CONTRACT_CUSTOM"
      override def isContractCustom: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends ContractClassification with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(CONTRACT_UNDEFINED, CONTRACT_SYSTEM, CONTRACT_CUSTOM)
    def fromValue(value: _root_.scala.Int): ContractClassification = value match {
      case 0 => CONTRACT_UNDEFINED
      case 1 => CONTRACT_SYSTEM
      case 2 => CONTRACT_CUSTOM
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.javaDescriptor.getEnumTypes.get(3)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.ChaincodeDeploy.scalaDescriptor.enums(3)
  }
  implicit class ChaincodeDeployLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeDeploy]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.ChaincodeDeploy](_l) {
    def timeout: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.timeout)((c_, f_) => c_.copy(timeout = f_))
    def codePackage: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.codePackage)((c_, f_) => c_.copy(codePackage = f_))
    def legalProse: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.legalProse)((c_, f_) => c_.copy(legalProse = f_))
    def cType: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeDeploy.CodeType] = field(_.cType)((c_, f_) => c_.copy(cType = f_))
    def rType: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeDeploy.RunType] = field(_.rType)((c_, f_) => c_.copy(rType = f_))
    def sType: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeDeploy.StateType] = field(_.sType)((c_, f_) => c_.copy(sType = f_))
    def initParameter: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.initParameter)((c_, f_) => c_.copy(initParameter = f_))
    def cclassification: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeDeploy.ContractClassification] = field(_.cclassification)((c_, f_) => c_.copy(cclassification = f_))
    def isCalledByOtherContracts: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isCalledByOtherContracts)((c_, f_) => c_.copy(isCalledByOtherContracts = f_))
  }
  final val TIMEOUT_FIELD_NUMBER = 1
  final val CODE_PACKAGE_FIELD_NUMBER = 2
  final val LEGAL_PROSE_FIELD_NUMBER = 3
  final val C_TYPE_FIELD_NUMBER = 4
  final val R_TYPE_FIELD_NUMBER = 5
  final val S_TYPE_FIELD_NUMBER = 6
  final val INIT_PARAMETER_FIELD_NUMBER = 7
  final val CCLASSIFICATION_FIELD_NUMBER = 8
  final val IS_CALLED_BY_OTHER_CONTRACTS_FIELD_NUMBER = 9
  def of(
    timeout: _root_.scala.Int,
    codePackage: _root_.scala.Predef.String,
    legalProse: _root_.scala.Predef.String,
    cType: rep.proto.rc2.ChaincodeDeploy.CodeType,
    rType: rep.proto.rc2.ChaincodeDeploy.RunType,
    sType: rep.proto.rc2.ChaincodeDeploy.StateType,
    initParameter: _root_.scala.Predef.String,
    cclassification: rep.proto.rc2.ChaincodeDeploy.ContractClassification,
    isCalledByOtherContracts: _root_.scala.Boolean,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.ChaincodeDeploy = _root_.rep.proto.rc2.ChaincodeDeploy(
    timeout,
    codePackage,
    legalProse,
    cType,
    rType,
    sType,
    initParameter,
    cclassification,
    isCalledByOtherContracts,
    unknownFields
  )
}
