// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** @param name
  *   凭据属性名称
  * @param type
  *   凭据属性值类型
  * @param required
  *   凭据是否必需包含该属性
  * @param description
  *   凭据属性描述
  */
@SerialVersionUID(0L)
final case class CreAttr(
    name: _root_.scala.Predef.String = "",
    `type`: _root_.scala.Predef.String = "",
    required: _root_.scala.Boolean = false,
    description: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[CreAttr] with scalapb.lenses.Updatable[CreAttr] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = `type`
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = required
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      
      {
        val __value = description
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = `type`
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = required
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      {
        val __v = description
        if (__v != "") {
          _output__.writeString(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.CreAttr = {
      var __name = this.name
      var __type = this.`type`
      var __required = this.required
      var __description = this.description
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readString()
          case 18 =>
            __type = _input__.readString()
          case 24 =>
            __required = _input__.readBool()
          case 34 =>
            __description = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.CreAttr(
          name = __name,
          `type` = __type,
          required = __required,
          description = __description,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withName(__v: _root_.scala.Predef.String): CreAttr = copy(name = __v)
    def withType(__v: _root_.scala.Predef.String): CreAttr = copy(`type` = __v)
    def withRequired(__v: _root_.scala.Boolean): CreAttr = copy(required = __v)
    def withDescription(__v: _root_.scala.Predef.String): CreAttr = copy(description = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = `type`
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = required
          if (__t != false) __t else null
        }
        case 4 => {
          val __t = description
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PString(`type`)
        case 3 => _root_.scalapb.descriptors.PBoolean(required)
        case 4 => _root_.scalapb.descriptors.PString(description)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.CreAttr
}

object CreAttr extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.CreAttr] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.CreAttr] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.CreAttr] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.CreAttr(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        `type` = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        required = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(8)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(8)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.CreAttr(
    name = "",
    `type` = "",
    required = false,
    description = ""
  )
  implicit class CreAttrLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.CreAttr]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.CreAttr](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
    def required: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.required)((c_, f_) => c_.copy(required = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val TYPE_FIELD_NUMBER = 2
  final val REQUIRED_FIELD_NUMBER = 3
  final val DESCRIPTION_FIELD_NUMBER = 4
  def of(
    name: _root_.scala.Predef.String,
    `type`: _root_.scala.Predef.String,
    required: _root_.scala.Boolean,
    description: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.CreAttr = _root_.rep.proto.rc2.CreAttr(
    name,
    `type`,
    required,
    description,
    unknownFields
  )
}
