// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 可验证凭据属性结构(CCS, Credential Claim Struct)
  *
  * @param version
  *   本数据结构的版本
  * @param id
  *   CCS唯一标识
  * @param name
  *   CCS名称
  * @param ccsVersion
  *   CCS版本
  * @param description
  *   CCS描述信息
  * @param creator
  *   CCS创建者did标识
  * @param created
  *   CCS创建时间
  * @param valid
  *   CCS有效性状态
  * @param attributes
  *   CCS属性
  */
@SerialVersionUID(0L)
final case class CreClaStruct(
    version: _root_.scala.Predef.String = "",
    id: _root_.scala.Predef.String = "",
    name: _root_.scala.Predef.String = "",
    ccsVersion: _root_.scala.Predef.String = "",
    description: _root_.scala.Predef.String = "",
    creator: _root_.scala.Predef.String = "",
    created: _root_.scala.Predef.String = "",
    valid: _root_.scala.Boolean = false,
    attributes: _root_.scala.Seq[rep.proto.rc2.CreAttr] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[CreClaStruct] with scalapb.lenses.Updatable[CreClaStruct] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = id
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = name
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = ccsVersion
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = description
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = creator
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = created
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      
      {
        val __value = valid
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(8, __value)
        }
      };
      attributes.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = id
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = name
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = ccsVersion
        if (__v != "") {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = description
        if (__v != "") {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = creator
        if (__v != "") {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = created
        if (__v != "") {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = valid
        if (__v != false) {
          _output__.writeBool(8, __v)
        }
      };
      attributes.foreach { __v =>
        val __m = __v
        _output__.writeTag(9, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.CreClaStruct = {
      var __version = this.version
      var __id = this.id
      var __name = this.name
      var __ccsVersion = this.ccsVersion
      var __description = this.description
      var __creator = this.creator
      var __created = this.created
      var __valid = this.valid
      val __attributes = (_root_.scala.collection.immutable.Vector.newBuilder[rep.proto.rc2.CreAttr] ++= this.attributes)
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __version = _input__.readString()
          case 18 =>
            __id = _input__.readString()
          case 26 =>
            __name = _input__.readString()
          case 34 =>
            __ccsVersion = _input__.readString()
          case 42 =>
            __description = _input__.readString()
          case 50 =>
            __creator = _input__.readString()
          case 58 =>
            __created = _input__.readString()
          case 64 =>
            __valid = _input__.readBool()
          case 74 =>
            __attributes += _root_.scalapb.LiteParser.readMessage(_input__, rep.proto.rc2.CreAttr.defaultInstance)
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.CreClaStruct(
          version = __version,
          id = __id,
          name = __name,
          ccsVersion = __ccsVersion,
          description = __description,
          creator = __creator,
          created = __created,
          valid = __valid,
          attributes = __attributes.result(),
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withVersion(__v: _root_.scala.Predef.String): CreClaStruct = copy(version = __v)
    def withId(__v: _root_.scala.Predef.String): CreClaStruct = copy(id = __v)
    def withName(__v: _root_.scala.Predef.String): CreClaStruct = copy(name = __v)
    def withCcsVersion(__v: _root_.scala.Predef.String): CreClaStruct = copy(ccsVersion = __v)
    def withDescription(__v: _root_.scala.Predef.String): CreClaStruct = copy(description = __v)
    def withCreator(__v: _root_.scala.Predef.String): CreClaStruct = copy(creator = __v)
    def withCreated(__v: _root_.scala.Predef.String): CreClaStruct = copy(created = __v)
    def withValid(__v: _root_.scala.Boolean): CreClaStruct = copy(valid = __v)
    def clearAttributes = copy(attributes = _root_.scala.Seq.empty)
    def addAttributes(__vs: rep.proto.rc2.CreAttr*): CreClaStruct = addAllAttributes(__vs)
    def addAllAttributes(__vs: Iterable[rep.proto.rc2.CreAttr]): CreClaStruct = copy(attributes = attributes ++ __vs)
    def withAttributes(__v: _root_.scala.Seq[rep.proto.rc2.CreAttr]): CreClaStruct = copy(attributes = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = version
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = ccsVersion
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = description
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = creator
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = created
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = valid
          if (__t != false) __t else null
        }
        case 9 => attributes
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(version)
        case 2 => _root_.scalapb.descriptors.PString(id)
        case 3 => _root_.scalapb.descriptors.PString(name)
        case 4 => _root_.scalapb.descriptors.PString(ccsVersion)
        case 5 => _root_.scalapb.descriptors.PString(description)
        case 6 => _root_.scalapb.descriptors.PString(creator)
        case 7 => _root_.scalapb.descriptors.PString(created)
        case 8 => _root_.scalapb.descriptors.PBoolean(valid)
        case 9 => _root_.scalapb.descriptors.PRepeated(attributes.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.CreClaStruct
}

object CreClaStruct extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.CreClaStruct] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.CreClaStruct] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.CreClaStruct] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.CreClaStruct(
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        ccsVersion = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        creator = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        created = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        valid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        attributes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Seq[rep.proto.rc2.CreAttr]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(7)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 9 => __out = rep.proto.rc2.CreAttr
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.CreClaStruct(
    version = "",
    id = "",
    name = "",
    ccsVersion = "",
    description = "",
    creator = "",
    created = "",
    valid = false,
    attributes = _root_.scala.Seq.empty
  )
  implicit class CreClaStructLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.CreClaStruct]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.CreClaStruct](_l) {
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def ccsVersion: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.ccsVersion)((c_, f_) => c_.copy(ccsVersion = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
    def creator: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.creator)((c_, f_) => c_.copy(creator = f_))
    def created: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.created)((c_, f_) => c_.copy(created = f_))
    def valid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.valid)((c_, f_) => c_.copy(valid = f_))
    def attributes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[rep.proto.rc2.CreAttr]] = field(_.attributes)((c_, f_) => c_.copy(attributes = f_))
  }
  final val VERSION_FIELD_NUMBER = 1
  final val ID_FIELD_NUMBER = 2
  final val NAME_FIELD_NUMBER = 3
  final val CCS_VERSION_FIELD_NUMBER = 4
  final val DESCRIPTION_FIELD_NUMBER = 5
  final val CREATOR_FIELD_NUMBER = 6
  final val CREATED_FIELD_NUMBER = 7
  final val VALID_FIELD_NUMBER = 8
  final val ATTRIBUTES_FIELD_NUMBER = 9
  def of(
    version: _root_.scala.Predef.String,
    id: _root_.scala.Predef.String,
    name: _root_.scala.Predef.String,
    ccsVersion: _root_.scala.Predef.String,
    description: _root_.scala.Predef.String,
    creator: _root_.scala.Predef.String,
    created: _root_.scala.Predef.String,
    valid: _root_.scala.Boolean,
    attributes: _root_.scala.Seq[rep.proto.rc2.CreAttr],
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.CreClaStruct = _root_.rep.proto.rc2.CreClaStruct(
    version,
    id,
    name,
    ccsVersion,
    description,
    creator,
    created,
    valid,
    attributes,
    unknownFields
  )
}
