// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** Event 用于图形展示的事件
  *
  * @param from
  *  来源addr
  * @param to
  *  发送addr，如果是广播（需要定义一个）
  */
@SerialVersionUID(0L)
final case class Event(
    from: _root_.scala.Predef.String = "",
    to: _root_.scala.Predef.String = "",
    action: rep.proto.rc2.Event.Action = rep.proto.rc2.Event.Action.SUBSCRIBE_TOPIC,
    blk: _root_.scala.Option[rep.proto.rc2.Block] = _root_.scala.None,
    contractEventContent: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Event] with scalapb.lenses.Updatable[Event] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = from
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = to
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = action
        if (__value != rep.proto.rc2.Event.Action.SUBSCRIBE_TOPIC) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value.value)
        }
      };
      if (blk.isDefined) {
        val __value = blk.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = contractEventContent
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = from
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = to
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = action
        if (__v != rep.proto.rc2.Event.Action.SUBSCRIBE_TOPIC) {
          _output__.writeEnum(3, __v.value)
        }
      };
      blk.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = contractEventContent
        if (__v != "") {
          _output__.writeString(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.Event = {
      var __from = this.from
      var __to = this.to
      var __action = this.action
      var __blk = this.blk
      var __contractEventContent = this.contractEventContent
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __from = _input__.readString()
          case 18 =>
            __to = _input__.readString()
          case 24 =>
            __action = rep.proto.rc2.Event.Action.fromValue(_input__.readEnum())
          case 34 =>
            __blk = Option(_root_.scalapb.LiteParser.readMessage(_input__, __blk.getOrElse(rep.proto.rc2.Block.defaultInstance)))
          case 42 =>
            __contractEventContent = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.Event(
          from = __from,
          to = __to,
          action = __action,
          blk = __blk,
          contractEventContent = __contractEventContent,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withFrom(__v: _root_.scala.Predef.String): Event = copy(from = __v)
    def withTo(__v: _root_.scala.Predef.String): Event = copy(to = __v)
    def withAction(__v: rep.proto.rc2.Event.Action): Event = copy(action = __v)
    def getBlk: rep.proto.rc2.Block = blk.getOrElse(rep.proto.rc2.Block.defaultInstance)
    def clearBlk: Event = copy(blk = _root_.scala.None)
    def withBlk(__v: rep.proto.rc2.Block): Event = copy(blk = Option(__v))
    def withContractEventContent(__v: _root_.scala.Predef.String): Event = copy(contractEventContent = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = from
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = to
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = action.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 4 => blk.orNull
        case 5 => {
          val __t = contractEventContent
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(from)
        case 2 => _root_.scalapb.descriptors.PString(to)
        case 3 => _root_.scalapb.descriptors.PEnum(action.scalaValueDescriptor)
        case 4 => blk.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 5 => _root_.scalapb.descriptors.PString(contractEventContent)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.Event
}

object Event extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.Event] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.Event] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.Event] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.Event(
        from = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        to = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        action = rep.proto.rc2.Event.Action.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.Event.Action.SUBSCRIBE_TOPIC.scalaValueDescriptor).number),
        blk = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.Block]]),
        contractEventContent = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = rep.proto.rc2.Block
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 3 => rep.proto.rc2.Event.Action
    }
  }
  lazy val defaultInstance = rep.proto.rc2.Event(
    from = "",
    to = "",
    action = rep.proto.rc2.Event.Action.SUBSCRIBE_TOPIC,
    blk = _root_.scala.None,
    contractEventContent = ""
  )
  /** event事件
    */
  sealed trait Action extends _root_.scalapb.GeneratedEnum {
    type EnumType = Action
    def isSubscribeTopic: _root_.scala.Boolean = false
    def isTransaction: _root_.scala.Boolean = false
    def isBlockNew: _root_.scala.Boolean = false
    def isBlockEndorsement: _root_.scala.Boolean = false
    def isEndorsement: _root_.scala.Boolean = false
    def isMemberUp: _root_.scala.Boolean = false
    def isMemberDown: _root_.scala.Boolean = false
    def isCandidator: _root_.scala.Boolean = false
    def isGenesisBlock: _root_.scala.Boolean = false
    def isBlockSync: _root_.scala.Boolean = false
    def isBlockSyncData: _root_.scala.Boolean = false
    def isBlockSyncSuc: _root_.scala.Boolean = false
    def isContractEvent: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[Action] = rep.proto.rc2.Event.Action
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.Event.Action.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.Event.Action.Recognized])
  }
  
  object Action extends _root_.scalapb.GeneratedEnumCompanion[Action] {
    sealed trait Recognized extends Action
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Action] = this
    @SerialVersionUID(0L)
    case object SUBSCRIBE_TOPIC extends Action with Action.Recognized {
      val value = 0
      val index = 0
      val name = "SUBSCRIBE_TOPIC"
      override def isSubscribeTopic: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object TRANSACTION extends Action with Action.Recognized {
      val value = 1
      val index = 1
      val name = "TRANSACTION"
      override def isTransaction: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object BLOCK_NEW extends Action with Action.Recognized {
      val value = 2
      val index = 2
      val name = "BLOCK_NEW"
      override def isBlockNew: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object BLOCK_ENDORSEMENT extends Action with Action.Recognized {
      val value = 3
      val index = 3
      val name = "BLOCK_ENDORSEMENT"
      override def isBlockEndorsement: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object ENDORSEMENT extends Action with Action.Recognized {
      val value = 4
      val index = 4
      val name = "ENDORSEMENT"
      override def isEndorsement: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object MEMBER_UP extends Action with Action.Recognized {
      val value = 5
      val index = 5
      val name = "MEMBER_UP"
      override def isMemberUp: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object MEMBER_DOWN extends Action with Action.Recognized {
      val value = 6
      val index = 6
      val name = "MEMBER_DOWN"
      override def isMemberDown: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CANDIDATOR extends Action with Action.Recognized {
      val value = 7
      val index = 7
      val name = "CANDIDATOR"
      override def isCandidator: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object GENESIS_BLOCK extends Action with Action.Recognized {
      val value = 8
      val index = 8
      val name = "GENESIS_BLOCK"
      override def isGenesisBlock: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object BLOCK_SYNC extends Action with Action.Recognized {
      val value = 9
      val index = 9
      val name = "BLOCK_SYNC"
      override def isBlockSync: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object BLOCK_SYNC_DATA extends Action with Action.Recognized {
      val value = 10
      val index = 10
      val name = "BLOCK_SYNC_DATA"
      override def isBlockSyncData: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object BLOCK_SYNC_SUC extends Action with Action.Recognized {
      val value = 11
      val index = 11
      val name = "BLOCK_SYNC_SUC"
      override def isBlockSyncSuc: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object CONTRACT_EVENT extends Action with Action.Recognized {
      val value = 12
      val index = 12
      val name = "CONTRACT_EVENT"
      override def isContractEvent: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends Action with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(SUBSCRIBE_TOPIC, TRANSACTION, BLOCK_NEW, BLOCK_ENDORSEMENT, ENDORSEMENT, MEMBER_UP, MEMBER_DOWN, CANDIDATOR, GENESIS_BLOCK, BLOCK_SYNC, BLOCK_SYNC_DATA, BLOCK_SYNC_SUC, CONTRACT_EVENT)
    def fromValue(value: _root_.scala.Int): Action = value match {
      case 0 => SUBSCRIBE_TOPIC
      case 1 => TRANSACTION
      case 2 => BLOCK_NEW
      case 3 => BLOCK_ENDORSEMENT
      case 4 => ENDORSEMENT
      case 5 => MEMBER_UP
      case 6 => MEMBER_DOWN
      case 7 => CANDIDATOR
      case 8 => GENESIS_BLOCK
      case 9 => BLOCK_SYNC
      case 10 => BLOCK_SYNC_DATA
      case 11 => BLOCK_SYNC_SUC
      case 12 => CONTRACT_EVENT
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.Event.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.Event.scalaDescriptor.enums(0)
  }
  implicit class EventLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Event]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.Event](_l) {
    def from: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.from)((c_, f_) => c_.copy(from = f_))
    def to: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.to)((c_, f_) => c_.copy(to = f_))
    def action: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Event.Action] = field(_.action)((c_, f_) => c_.copy(action = f_))
    def blk: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Block] = field(_.getBlk)((c_, f_) => c_.copy(blk = Option(f_)))
    def optionalBlk: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[rep.proto.rc2.Block]] = field(_.blk)((c_, f_) => c_.copy(blk = f_))
    def contractEventContent: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.contractEventContent)((c_, f_) => c_.copy(contractEventContent = f_))
  }
  final val FROM_FIELD_NUMBER = 1
  final val TO_FIELD_NUMBER = 2
  final val ACTION_FIELD_NUMBER = 3
  final val BLK_FIELD_NUMBER = 4
  final val CONTRACT_EVENT_CONTENT_FIELD_NUMBER = 5
  def of(
    from: _root_.scala.Predef.String,
    to: _root_.scala.Predef.String,
    action: rep.proto.rc2.Event.Action,
    blk: _root_.scala.Option[rep.proto.rc2.Block],
    contractEventContent: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.Event = _root_.rep.proto.rc2.Event(
    from,
    to,
    action,
    blk,
    contractEventContent,
    unknownFields
  )
}
