// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** @param opId
  *  操作的id，通过uuid自动生成，合约需要查重
  * @param description
  *  操作的描述，用于显示
  * @param register
  *  操作的注册者，使用credit code或者rdid
  * @param isPublish
  *  操作是否属于公开，公开表示不需要授权，只要拥有rdid就可以调用；不公开，需要授权；默认false
  * @param operateType
  *  操作类型表示是否属于服务类型，服务类型只需要提供服务器和服务名就可以；如果是合约方式，需要提供合约方法的访问；
  * @param operateServiceName
  *  服务名称
  * @param operateEndpoint
  *  服务器地址
  * @param authFullName
  *  限制内容，具体操作限制，如访问的链的合约的方法
  * @param createTime
  *  建立时间
  * @param disableTime
  *  禁用时间
  * @param opValid
  *  是否有效，默认有效，否则为禁用，值=false
  * @param version
  *  默认1.0
  */
@SerialVersionUID(0L)
final case class Operate(
    opId: _root_.scala.Predef.String = "",
    description: _root_.scala.Predef.String = "",
    register: _root_.scala.Predef.String = "",
    isPublish: _root_.scala.Boolean = false,
    operateType: rep.proto.rc2.Operate.OperateType = rep.proto.rc2.Operate.OperateType.OPERATE_UNDEFINED,
    operateServiceName: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    operateEndpoint: _root_.scala.Predef.String = "",
    authFullName: _root_.scala.Predef.String = "",
    createTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    disableTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    opValid: _root_.scala.Boolean = false,
    version: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Operate] with scalapb.lenses.Updatable[Operate] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = opId
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = description
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = register
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = isPublish
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(4, __value)
        }
      };
      
      {
        val __value = operateType
        if (__value != rep.proto.rc2.Operate.OperateType.OPERATE_UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value.value)
        }
      };
      operateServiceName.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
      }
      
      {
        val __value = operateEndpoint
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      
      {
        val __value = authFullName
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      if (createTime.isDefined) {
        val __value = createTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (disableTime.isDefined) {
        val __value = disableTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = opValid
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(11, __value)
        }
      };
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(12, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = opId
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = description
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = register
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = isPublish
        if (__v != false) {
          _output__.writeBool(4, __v)
        }
      };
      {
        val __v = operateType
        if (__v != rep.proto.rc2.Operate.OperateType.OPERATE_UNDEFINED) {
          _output__.writeEnum(5, __v.value)
        }
      };
      operateServiceName.foreach { __v =>
        val __m = __v
        _output__.writeString(6, __m)
      };
      {
        val __v = operateEndpoint
        if (__v != "") {
          _output__.writeString(7, __v)
        }
      };
      {
        val __v = authFullName
        if (__v != "") {
          _output__.writeString(8, __v)
        }
      };
      createTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(9, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      disableTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(10, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = opValid
        if (__v != false) {
          _output__.writeBool(11, __v)
        }
      };
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(12, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.Operate = {
      var __opId = this.opId
      var __description = this.description
      var __register = this.register
      var __isPublish = this.isPublish
      var __operateType = this.operateType
      val __operateServiceName = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.operateServiceName)
      var __operateEndpoint = this.operateEndpoint
      var __authFullName = this.authFullName
      var __createTime = this.createTime
      var __disableTime = this.disableTime
      var __opValid = this.opValid
      var __version = this.version
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __opId = _input__.readString()
          case 18 =>
            __description = _input__.readString()
          case 26 =>
            __register = _input__.readString()
          case 32 =>
            __isPublish = _input__.readBool()
          case 40 =>
            __operateType = rep.proto.rc2.Operate.OperateType.fromValue(_input__.readEnum())
          case 50 =>
            __operateServiceName += _input__.readString()
          case 58 =>
            __operateEndpoint = _input__.readString()
          case 66 =>
            __authFullName = _input__.readString()
          case 74 =>
            __createTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __createTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 82 =>
            __disableTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __disableTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 88 =>
            __opValid = _input__.readBool()
          case 98 =>
            __version = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.Operate(
          opId = __opId,
          description = __description,
          register = __register,
          isPublish = __isPublish,
          operateType = __operateType,
          operateServiceName = __operateServiceName.result(),
          operateEndpoint = __operateEndpoint,
          authFullName = __authFullName,
          createTime = __createTime,
          disableTime = __disableTime,
          opValid = __opValid,
          version = __version,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withOpId(__v: _root_.scala.Predef.String): Operate = copy(opId = __v)
    def withDescription(__v: _root_.scala.Predef.String): Operate = copy(description = __v)
    def withRegister(__v: _root_.scala.Predef.String): Operate = copy(register = __v)
    def withIsPublish(__v: _root_.scala.Boolean): Operate = copy(isPublish = __v)
    def withOperateType(__v: rep.proto.rc2.Operate.OperateType): Operate = copy(operateType = __v)
    def clearOperateServiceName = copy(operateServiceName = _root_.scala.Seq.empty)
    def addOperateServiceName(__vs: _root_.scala.Predef.String*): Operate = addAllOperateServiceName(__vs)
    def addAllOperateServiceName(__vs: Iterable[_root_.scala.Predef.String]): Operate = copy(operateServiceName = operateServiceName ++ __vs)
    def withOperateServiceName(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Operate = copy(operateServiceName = __v)
    def withOperateEndpoint(__v: _root_.scala.Predef.String): Operate = copy(operateEndpoint = __v)
    def withAuthFullName(__v: _root_.scala.Predef.String): Operate = copy(authFullName = __v)
    def getCreateTime: com.google.protobuf.timestamp.Timestamp = createTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearCreateTime: Operate = copy(createTime = _root_.scala.None)
    def withCreateTime(__v: com.google.protobuf.timestamp.Timestamp): Operate = copy(createTime = Option(__v))
    def getDisableTime: com.google.protobuf.timestamp.Timestamp = disableTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearDisableTime: Operate = copy(disableTime = _root_.scala.None)
    def withDisableTime(__v: com.google.protobuf.timestamp.Timestamp): Operate = copy(disableTime = Option(__v))
    def withOpValid(__v: _root_.scala.Boolean): Operate = copy(opValid = __v)
    def withVersion(__v: _root_.scala.Predef.String): Operate = copy(version = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = opId
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = description
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = register
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = isPublish
          if (__t != false) __t else null
        }
        case 5 => {
          val __t = operateType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 6 => operateServiceName
        case 7 => {
          val __t = operateEndpoint
          if (__t != "") __t else null
        }
        case 8 => {
          val __t = authFullName
          if (__t != "") __t else null
        }
        case 9 => createTime.orNull
        case 10 => disableTime.orNull
        case 11 => {
          val __t = opValid
          if (__t != false) __t else null
        }
        case 12 => {
          val __t = version
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(opId)
        case 2 => _root_.scalapb.descriptors.PString(description)
        case 3 => _root_.scalapb.descriptors.PString(register)
        case 4 => _root_.scalapb.descriptors.PBoolean(isPublish)
        case 5 => _root_.scalapb.descriptors.PEnum(operateType.scalaValueDescriptor)
        case 6 => _root_.scalapb.descriptors.PRepeated(operateServiceName.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 7 => _root_.scalapb.descriptors.PString(operateEndpoint)
        case 8 => _root_.scalapb.descriptors.PString(authFullName)
        case 9 => createTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 10 => disableTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 11 => _root_.scalapb.descriptors.PBoolean(opValid)
        case 12 => _root_.scalapb.descriptors.PString(version)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.Operate
}

object Operate extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.Operate] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.Operate] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.Operate] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.Operate(
        opId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        register = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        isPublish = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        operateType = rep.proto.rc2.Operate.OperateType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.Operate.OperateType.OPERATE_UNDEFINED.scalaValueDescriptor).number),
        operateServiceName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        operateEndpoint = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        authFullName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        createTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        disableTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        opValid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(12).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(4)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 9 => __out = com.google.protobuf.timestamp.Timestamp
      case 10 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 5 => rep.proto.rc2.Operate.OperateType
    }
  }
  lazy val defaultInstance = rep.proto.rc2.Operate(
    opId = "",
    description = "",
    register = "",
    isPublish = false,
    operateType = rep.proto.rc2.Operate.OperateType.OPERATE_UNDEFINED,
    operateServiceName = _root_.scala.Seq.empty,
    operateEndpoint = "",
    authFullName = "",
    createTime = _root_.scala.None,
    disableTime = _root_.scala.None,
    opValid = false,
    version = ""
  )
  sealed trait OperateType extends _root_.scalapb.GeneratedEnum {
    type EnumType = OperateType
    def isOperateUndefined: _root_.scala.Boolean = false
    def isOperateContract: _root_.scala.Boolean = false
    def isOperateService: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[OperateType] = rep.proto.rc2.Operate.OperateType
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.Operate.OperateType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.Operate.OperateType.Recognized])
  }
  
  object OperateType extends _root_.scalapb.GeneratedEnumCompanion[OperateType] {
    sealed trait Recognized extends OperateType
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[OperateType] = this
    @SerialVersionUID(0L)
    case object OPERATE_UNDEFINED extends OperateType with OperateType.Recognized {
      val value = 0
      val index = 0
      val name = "OPERATE_UNDEFINED"
      override def isOperateUndefined: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object OPERATE_CONTRACT extends OperateType with OperateType.Recognized {
      val value = 1
      val index = 1
      val name = "OPERATE_CONTRACT"
      override def isOperateContract: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object OPERATE_SERVICE extends OperateType with OperateType.Recognized {
      val value = 2
      val index = 2
      val name = "OPERATE_SERVICE"
      override def isOperateService: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends OperateType with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(OPERATE_UNDEFINED, OPERATE_CONTRACT, OPERATE_SERVICE)
    def fromValue(value: _root_.scala.Int): OperateType = value match {
      case 0 => OPERATE_UNDEFINED
      case 1 => OPERATE_CONTRACT
      case 2 => OPERATE_SERVICE
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.Operate.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.Operate.scalaDescriptor.enums(0)
  }
  implicit class OperateLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Operate]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.Operate](_l) {
    def opId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.opId)((c_, f_) => c_.copy(opId = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
    def register: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.register)((c_, f_) => c_.copy(register = f_))
    def isPublish: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isPublish)((c_, f_) => c_.copy(isPublish = f_))
    def operateType: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Operate.OperateType] = field(_.operateType)((c_, f_) => c_.copy(operateType = f_))
    def operateServiceName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.operateServiceName)((c_, f_) => c_.copy(operateServiceName = f_))
    def operateEndpoint: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.operateEndpoint)((c_, f_) => c_.copy(operateEndpoint = f_))
    def authFullName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.authFullName)((c_, f_) => c_.copy(authFullName = f_))
    def createTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getCreateTime)((c_, f_) => c_.copy(createTime = Option(f_)))
    def optionalCreateTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.createTime)((c_, f_) => c_.copy(createTime = f_))
    def disableTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getDisableTime)((c_, f_) => c_.copy(disableTime = Option(f_)))
    def optionalDisableTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.disableTime)((c_, f_) => c_.copy(disableTime = f_))
    def opValid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.opValid)((c_, f_) => c_.copy(opValid = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
  }
  final val OP_ID_FIELD_NUMBER = 1
  final val DESCRIPTION_FIELD_NUMBER = 2
  final val REGISTER_FIELD_NUMBER = 3
  final val IS_PUBLISH_FIELD_NUMBER = 4
  final val OPERATE_TYPE_FIELD_NUMBER = 5
  final val OPERATE_SERVICE_NAME_FIELD_NUMBER = 6
  final val OPERATE_ENDPOINT_FIELD_NUMBER = 7
  final val AUTH_FULL_NAME_FIELD_NUMBER = 8
  final val CREATE_TIME_FIELD_NUMBER = 9
  final val DISABLE_TIME_FIELD_NUMBER = 10
  final val OP_VALID_FIELD_NUMBER = 11
  final val VERSION_FIELD_NUMBER = 12
  def of(
    opId: _root_.scala.Predef.String,
    description: _root_.scala.Predef.String,
    register: _root_.scala.Predef.String,
    isPublish: _root_.scala.Boolean,
    operateType: rep.proto.rc2.Operate.OperateType,
    operateServiceName: _root_.scala.Seq[_root_.scala.Predef.String],
    operateEndpoint: _root_.scala.Predef.String,
    authFullName: _root_.scala.Predef.String,
    createTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    disableTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    opValid: _root_.scala.Boolean,
    version: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.Operate = _root_.rep.proto.rc2.Operate(
    opId,
    description,
    register,
    isPublish,
    operateType,
    operateServiceName,
    operateEndpoint,
    authFullName,
    createTime,
    disableTime,
    opValid,
    version,
    unknownFields
  )
}
