// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 账户
  *
  * @param name
  *  注册者的名称或者昵称
  * @param creditCode
  *  社会信用代码（个人或机构）或者DID，推荐使用DID
  * @param mobile
  *   手机号码,用于接收通知
  * @param certNames
  *  存放用户所有证书的名称，用户具体的证书单独存放，方便证书的操作，用户在增加证书的时候，在这个列表中增加证书的名称，did_certname。
  * @param authorizeIds
  *  存放用户所有授权的操作id。
  * @param operateIds
  *  存放用户所有注册的操作id。
  * @param credentialMetadataIds
  *  存放用户凭据id。
  * @param authenticationCerts
  *  存放身份验证证书
  * @param signerInfo
  *  存放用户身份的详细信息，采用json格式。通常不用存储，由身份管理者存储
  * @param createTime
  *  建立时间
  * @param disableTime
  *  禁用时间
  * @param signerValid
  *  是否有效，默认有效，否则为禁用，值=false
  * @param version
  *  默认1.0
  */
@SerialVersionUID(0L)
final case class Signer(
    name: _root_.scala.Predef.String = "",
    creditCode: _root_.scala.Predef.String = "",
    mobile: _root_.scala.Predef.String = "",
    certNames: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    authorizeIds: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    operateIds: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    credentialMetadataIds: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    authenticationCerts: _root_.scala.Seq[rep.proto.rc2.Certificate] = _root_.scala.Seq.empty,
    signerInfo: _root_.scala.Predef.String = "",
    createTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    disableTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None,
    signerValid: _root_.scala.Boolean = false,
    version: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Signer] with scalapb.lenses.Updatable[Signer] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = creditCode
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = mobile
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      certNames.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
      }
      authorizeIds.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
      }
      operateIds.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
      }
      credentialMetadataIds.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
      }
      authenticationCerts.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = signerInfo
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
        }
      };
      if (createTime.isDefined) {
        val __value = createTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (disableTime.isDefined) {
        val __value = disableTime.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = signerValid
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(12, __value)
        }
      };
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(13, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = creditCode
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = mobile
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      certNames.foreach { __v =>
        val __m = __v
        _output__.writeString(4, __m)
      };
      authorizeIds.foreach { __v =>
        val __m = __v
        _output__.writeString(5, __m)
      };
      operateIds.foreach { __v =>
        val __m = __v
        _output__.writeString(6, __m)
      };
      credentialMetadataIds.foreach { __v =>
        val __m = __v
        _output__.writeString(7, __m)
      };
      authenticationCerts.foreach { __v =>
        val __m = __v
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = signerInfo
        if (__v != "") {
          _output__.writeString(9, __v)
        }
      };
      createTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(10, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      disableTime.foreach { __v =>
        val __m = __v
        _output__.writeTag(11, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = signerValid
        if (__v != false) {
          _output__.writeBool(12, __v)
        }
      };
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(13, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.Signer = {
      var __name = this.name
      var __creditCode = this.creditCode
      var __mobile = this.mobile
      val __certNames = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.certNames)
      val __authorizeIds = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.authorizeIds)
      val __operateIds = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.operateIds)
      val __credentialMetadataIds = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.credentialMetadataIds)
      val __authenticationCerts = (_root_.scala.collection.immutable.Vector.newBuilder[rep.proto.rc2.Certificate] ++= this.authenticationCerts)
      var __signerInfo = this.signerInfo
      var __createTime = this.createTime
      var __disableTime = this.disableTime
      var __signerValid = this.signerValid
      var __version = this.version
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readString()
          case 18 =>
            __creditCode = _input__.readString()
          case 26 =>
            __mobile = _input__.readString()
          case 34 =>
            __certNames += _input__.readString()
          case 42 =>
            __authorizeIds += _input__.readString()
          case 50 =>
            __operateIds += _input__.readString()
          case 58 =>
            __credentialMetadataIds += _input__.readString()
          case 66 =>
            __authenticationCerts += _root_.scalapb.LiteParser.readMessage(_input__, rep.proto.rc2.Certificate.defaultInstance)
          case 74 =>
            __signerInfo = _input__.readString()
          case 82 =>
            __createTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __createTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 90 =>
            __disableTime = Option(_root_.scalapb.LiteParser.readMessage(_input__, __disableTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)))
          case 96 =>
            __signerValid = _input__.readBool()
          case 106 =>
            __version = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.Signer(
          name = __name,
          creditCode = __creditCode,
          mobile = __mobile,
          certNames = __certNames.result(),
          authorizeIds = __authorizeIds.result(),
          operateIds = __operateIds.result(),
          credentialMetadataIds = __credentialMetadataIds.result(),
          authenticationCerts = __authenticationCerts.result(),
          signerInfo = __signerInfo,
          createTime = __createTime,
          disableTime = __disableTime,
          signerValid = __signerValid,
          version = __version,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withName(__v: _root_.scala.Predef.String): Signer = copy(name = __v)
    def withCreditCode(__v: _root_.scala.Predef.String): Signer = copy(creditCode = __v)
    def withMobile(__v: _root_.scala.Predef.String): Signer = copy(mobile = __v)
    def clearCertNames = copy(certNames = _root_.scala.Seq.empty)
    def addCertNames(__vs: _root_.scala.Predef.String*): Signer = addAllCertNames(__vs)
    def addAllCertNames(__vs: Iterable[_root_.scala.Predef.String]): Signer = copy(certNames = certNames ++ __vs)
    def withCertNames(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Signer = copy(certNames = __v)
    def clearAuthorizeIds = copy(authorizeIds = _root_.scala.Seq.empty)
    def addAuthorizeIds(__vs: _root_.scala.Predef.String*): Signer = addAllAuthorizeIds(__vs)
    def addAllAuthorizeIds(__vs: Iterable[_root_.scala.Predef.String]): Signer = copy(authorizeIds = authorizeIds ++ __vs)
    def withAuthorizeIds(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Signer = copy(authorizeIds = __v)
    def clearOperateIds = copy(operateIds = _root_.scala.Seq.empty)
    def addOperateIds(__vs: _root_.scala.Predef.String*): Signer = addAllOperateIds(__vs)
    def addAllOperateIds(__vs: Iterable[_root_.scala.Predef.String]): Signer = copy(operateIds = operateIds ++ __vs)
    def withOperateIds(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Signer = copy(operateIds = __v)
    def clearCredentialMetadataIds = copy(credentialMetadataIds = _root_.scala.Seq.empty)
    def addCredentialMetadataIds(__vs: _root_.scala.Predef.String*): Signer = addAllCredentialMetadataIds(__vs)
    def addAllCredentialMetadataIds(__vs: Iterable[_root_.scala.Predef.String]): Signer = copy(credentialMetadataIds = credentialMetadataIds ++ __vs)
    def withCredentialMetadataIds(__v: _root_.scala.Seq[_root_.scala.Predef.String]): Signer = copy(credentialMetadataIds = __v)
    def clearAuthenticationCerts = copy(authenticationCerts = _root_.scala.Seq.empty)
    def addAuthenticationCerts(__vs: rep.proto.rc2.Certificate*): Signer = addAllAuthenticationCerts(__vs)
    def addAllAuthenticationCerts(__vs: Iterable[rep.proto.rc2.Certificate]): Signer = copy(authenticationCerts = authenticationCerts ++ __vs)
    def withAuthenticationCerts(__v: _root_.scala.Seq[rep.proto.rc2.Certificate]): Signer = copy(authenticationCerts = __v)
    def withSignerInfo(__v: _root_.scala.Predef.String): Signer = copy(signerInfo = __v)
    def getCreateTime: com.google.protobuf.timestamp.Timestamp = createTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearCreateTime: Signer = copy(createTime = _root_.scala.None)
    def withCreateTime(__v: com.google.protobuf.timestamp.Timestamp): Signer = copy(createTime = Option(__v))
    def getDisableTime: com.google.protobuf.timestamp.Timestamp = disableTime.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance)
    def clearDisableTime: Signer = copy(disableTime = _root_.scala.None)
    def withDisableTime(__v: com.google.protobuf.timestamp.Timestamp): Signer = copy(disableTime = Option(__v))
    def withSignerValid(__v: _root_.scala.Boolean): Signer = copy(signerValid = __v)
    def withVersion(__v: _root_.scala.Predef.String): Signer = copy(version = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = creditCode
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = mobile
          if (__t != "") __t else null
        }
        case 4 => certNames
        case 5 => authorizeIds
        case 6 => operateIds
        case 7 => credentialMetadataIds
        case 8 => authenticationCerts
        case 9 => {
          val __t = signerInfo
          if (__t != "") __t else null
        }
        case 10 => createTime.orNull
        case 11 => disableTime.orNull
        case 12 => {
          val __t = signerValid
          if (__t != false) __t else null
        }
        case 13 => {
          val __t = version
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PString(creditCode)
        case 3 => _root_.scalapb.descriptors.PString(mobile)
        case 4 => _root_.scalapb.descriptors.PRepeated(certNames.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 5 => _root_.scalapb.descriptors.PRepeated(authorizeIds.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 6 => _root_.scalapb.descriptors.PRepeated(operateIds.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 7 => _root_.scalapb.descriptors.PRepeated(credentialMetadataIds.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 8 => _root_.scalapb.descriptors.PRepeated(authenticationCerts.iterator.map(_.toPMessage).toVector)
        case 9 => _root_.scalapb.descriptors.PString(signerInfo)
        case 10 => createTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 11 => disableTime.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 12 => _root_.scalapb.descriptors.PBoolean(signerValid)
        case 13 => _root_.scalapb.descriptors.PString(version)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.Signer
}

object Signer extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.Signer] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.Signer] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.Signer] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.Signer(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        creditCode = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        mobile = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        certNames = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        authorizeIds = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        operateIds = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        credentialMetadataIds = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        authenticationCerts = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Seq[rep.proto.rc2.Certificate]]).getOrElse(_root_.scala.Seq.empty),
        signerInfo = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        createTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        disableTime = __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.timestamp.Timestamp]]),
        signerValid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(12).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(13).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 8 => __out = rep.proto.rc2.Certificate
      case 10 => __out = com.google.protobuf.timestamp.Timestamp
      case 11 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.Signer(
    name = "",
    creditCode = "",
    mobile = "",
    certNames = _root_.scala.Seq.empty,
    authorizeIds = _root_.scala.Seq.empty,
    operateIds = _root_.scala.Seq.empty,
    credentialMetadataIds = _root_.scala.Seq.empty,
    authenticationCerts = _root_.scala.Seq.empty,
    signerInfo = "",
    createTime = _root_.scala.None,
    disableTime = _root_.scala.None,
    signerValid = false,
    version = ""
  )
  implicit class SignerLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Signer]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.Signer](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def creditCode: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.creditCode)((c_, f_) => c_.copy(creditCode = f_))
    def mobile: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.mobile)((c_, f_) => c_.copy(mobile = f_))
    def certNames: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.certNames)((c_, f_) => c_.copy(certNames = f_))
    def authorizeIds: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.authorizeIds)((c_, f_) => c_.copy(authorizeIds = f_))
    def operateIds: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.operateIds)((c_, f_) => c_.copy(operateIds = f_))
    def credentialMetadataIds: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.credentialMetadataIds)((c_, f_) => c_.copy(credentialMetadataIds = f_))
    def authenticationCerts: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[rep.proto.rc2.Certificate]] = field(_.authenticationCerts)((c_, f_) => c_.copy(authenticationCerts = f_))
    def signerInfo: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.signerInfo)((c_, f_) => c_.copy(signerInfo = f_))
    def createTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getCreateTime)((c_, f_) => c_.copy(createTime = Option(f_)))
    def optionalCreateTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.createTime)((c_, f_) => c_.copy(createTime = f_))
    def disableTime: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.getDisableTime)((c_, f_) => c_.copy(disableTime = Option(f_)))
    def optionalDisableTime: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.timestamp.Timestamp]] = field(_.disableTime)((c_, f_) => c_.copy(disableTime = f_))
    def signerValid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.signerValid)((c_, f_) => c_.copy(signerValid = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val CREDIT_CODE_FIELD_NUMBER = 2
  final val MOBILE_FIELD_NUMBER = 3
  final val CERT_NAMES_FIELD_NUMBER = 4
  final val AUTHORIZE_IDS_FIELD_NUMBER = 5
  final val OPERATE_IDS_FIELD_NUMBER = 6
  final val CREDENTIAL_METADATA_IDS_FIELD_NUMBER = 7
  final val AUTHENTICATION_CERTS_FIELD_NUMBER = 8
  final val SIGNER_INFO_FIELD_NUMBER = 9
  final val CREATE_TIME_FIELD_NUMBER = 10
  final val DISABLE_TIME_FIELD_NUMBER = 11
  final val SIGNER_VALID_FIELD_NUMBER = 12
  final val VERSION_FIELD_NUMBER = 13
  def of(
    name: _root_.scala.Predef.String,
    creditCode: _root_.scala.Predef.String,
    mobile: _root_.scala.Predef.String,
    certNames: _root_.scala.Seq[_root_.scala.Predef.String],
    authorizeIds: _root_.scala.Seq[_root_.scala.Predef.String],
    operateIds: _root_.scala.Seq[_root_.scala.Predef.String],
    credentialMetadataIds: _root_.scala.Seq[_root_.scala.Predef.String],
    authenticationCerts: _root_.scala.Seq[rep.proto.rc2.Certificate],
    signerInfo: _root_.scala.Predef.String,
    createTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    disableTime: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp],
    signerValid: _root_.scala.Boolean,
    version: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.Signer = _root_.rep.proto.rc2.Signer(
    name,
    creditCode,
    mobile,
    certNames,
    authorizeIds,
    operateIds,
    credentialMetadataIds,
    authenticationCerts,
    signerInfo,
    createTime,
    disableTime,
    signerValid,
    version,
    unknownFields
  )
}
