// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 交易执行结果
  *
  * @param txId
  *  唯一标识一个Transaction
  * @param statesGet
  *  交易读取状态集合
  * @param statesSet
  *  交易写入/迁移状态集合
  * @param statesDel
  *  交易删除状态集合
  */
@SerialVersionUID(0L)
final case class TransactionResult(
    txId: _root_.scala.Predef.String = "",
    statesGet: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] = _root_.scala.collection.immutable.Map.empty,
    statesSet: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] = _root_.scala.collection.immutable.Map.empty,
    statesDel: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] = _root_.scala.collection.immutable.Map.empty,
    err: _root_.scala.Option[rep.proto.rc2.ActionResult] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[TransactionResult] with scalapb.lenses.Updatable[TransactionResult] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = txId
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      statesGet.foreach { __item =>
        val __value = rep.proto.rc2.TransactionResult._typemapper_statesGet.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      statesSet.foreach { __item =>
        val __value = rep.proto.rc2.TransactionResult._typemapper_statesSet.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      statesDel.foreach { __item =>
        val __value = rep.proto.rc2.TransactionResult._typemapper_statesDel.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      if (err.isDefined) {
        val __value = err.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = txId
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      statesGet.foreach { __v =>
        val __m = rep.proto.rc2.TransactionResult._typemapper_statesGet.toBase(__v)
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      statesSet.foreach { __v =>
        val __m = rep.proto.rc2.TransactionResult._typemapper_statesSet.toBase(__v)
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      statesDel.foreach { __v =>
        val __m = rep.proto.rc2.TransactionResult._typemapper_statesDel.toBase(__v)
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      err.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.TransactionResult = {
      var __txId = this.txId
      val __statesGet = (_root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] ++= this.statesGet)
      val __statesSet = (_root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] ++= this.statesSet)
      val __statesDel = (_root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] ++= this.statesDel)
      var __err = this.err
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __txId = _input__.readString()
          case 18 =>
            __statesGet += rep.proto.rc2.TransactionResult._typemapper_statesGet.toCustom(_root_.scalapb.LiteParser.readMessage(_input__, rep.proto.rc2.TransactionResult.StatesGetEntry.defaultInstance))
          case 26 =>
            __statesSet += rep.proto.rc2.TransactionResult._typemapper_statesSet.toCustom(_root_.scalapb.LiteParser.readMessage(_input__, rep.proto.rc2.TransactionResult.StatesSetEntry.defaultInstance))
          case 34 =>
            __statesDel += rep.proto.rc2.TransactionResult._typemapper_statesDel.toCustom(_root_.scalapb.LiteParser.readMessage(_input__, rep.proto.rc2.TransactionResult.StatesDelEntry.defaultInstance))
          case 42 =>
            __err = Option(_root_.scalapb.LiteParser.readMessage(_input__, __err.getOrElse(rep.proto.rc2.ActionResult.defaultInstance)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.TransactionResult(
          txId = __txId,
          statesGet = __statesGet.result(),
          statesSet = __statesSet.result(),
          statesDel = __statesDel.result(),
          err = __err,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withTxId(__v: _root_.scala.Predef.String): TransactionResult = copy(txId = __v)
    def clearStatesGet = copy(statesGet = _root_.scala.collection.immutable.Map.empty)
    def addStatesGet(__vs: (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)*): TransactionResult = addAllStatesGet(__vs)
    def addAllStatesGet(__vs: Iterable[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]): TransactionResult = copy(statesGet = statesGet ++ __vs)
    def withStatesGet(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]): TransactionResult = copy(statesGet = __v)
    def clearStatesSet = copy(statesSet = _root_.scala.collection.immutable.Map.empty)
    def addStatesSet(__vs: (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)*): TransactionResult = addAllStatesSet(__vs)
    def addAllStatesSet(__vs: Iterable[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]): TransactionResult = copy(statesSet = statesSet ++ __vs)
    def withStatesSet(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]): TransactionResult = copy(statesSet = __v)
    def clearStatesDel = copy(statesDel = _root_.scala.collection.immutable.Map.empty)
    def addStatesDel(__vs: (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)*): TransactionResult = addAllStatesDel(__vs)
    def addAllStatesDel(__vs: Iterable[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]): TransactionResult = copy(statesDel = statesDel ++ __vs)
    def withStatesDel(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]): TransactionResult = copy(statesDel = __v)
    def getErr: rep.proto.rc2.ActionResult = err.getOrElse(rep.proto.rc2.ActionResult.defaultInstance)
    def clearErr: TransactionResult = copy(err = _root_.scala.None)
    def withErr(__v: rep.proto.rc2.ActionResult): TransactionResult = copy(err = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = txId
          if (__t != "") __t else null
        }
        case 2 => statesGet.iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesGet.toBase).toSeq
        case 3 => statesSet.iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesSet.toBase).toSeq
        case 4 => statesDel.iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesDel.toBase).toSeq
        case 5 => err.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(txId)
        case 2 => _root_.scalapb.descriptors.PRepeated(statesGet.iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesGet.toBase(_).toPMessage).toVector)
        case 3 => _root_.scalapb.descriptors.PRepeated(statesSet.iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesSet.toBase(_).toPMessage).toVector)
        case 4 => _root_.scalapb.descriptors.PRepeated(statesDel.iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesDel.toBase(_).toPMessage).toVector)
        case 5 => err.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.TransactionResult
}

object TransactionResult extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.TransactionResult] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.TransactionResult(
        txId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        statesGet = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[rep.proto.rc2.TransactionResult.StatesGetEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesGet.toCustom).toMap,
        statesSet = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[rep.proto.rc2.TransactionResult.StatesSetEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesSet.toCustom).toMap,
        statesDel = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[rep.proto.rc2.TransactionResult.StatesDelEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(rep.proto.rc2.TransactionResult._typemapper_statesDel.toCustom).toMap,
        err = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.ActionResult]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(16)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(16)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = rep.proto.rc2.TransactionResult.StatesGetEntry
      case 3 => __out = rep.proto.rc2.TransactionResult.StatesSetEntry
      case 4 => __out = rep.proto.rc2.TransactionResult.StatesDelEntry
      case 5 => __out = rep.proto.rc2.ActionResult
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.rep.proto.rc2.TransactionResult.StatesGetEntry,
      _root_.rep.proto.rc2.TransactionResult.StatesSetEntry,
      _root_.rep.proto.rc2.TransactionResult.StatesDelEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.TransactionResult(
    txId = "",
    statesGet = _root_.scala.collection.immutable.Map.empty,
    statesSet = _root_.scala.collection.immutable.Map.empty,
    statesDel = _root_.scala.collection.immutable.Map.empty,
    err = _root_.scala.None
  )
  @SerialVersionUID(0L)
  final case class StatesGetEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.Message[StatesGetEntry] with scalapb.lenses.Updatable[StatesGetEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (__value != "") {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = value
          if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = value
          if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
            _output__.writeBytes(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.TransactionResult.StatesGetEntry = {
        var __key = this.key
        var __value = this.value
        var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readString()
            case 18 =>
              __value = _input__.readBytes()
            case tag =>
              if (_unknownFields__ == null) {
                _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
              }
              _unknownFields__.parseField(tag, _input__)
          }
        }
        rep.proto.rc2.TransactionResult.StatesGetEntry(
            key = __key,
            value = __value,
            unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
        )
      }
      def withKey(__v: _root_.scala.Predef.String): StatesGetEntry = copy(key = __v)
      def withValue(__v: _root_.com.google.protobuf.ByteString): StatesGetEntry = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = value
            if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => _root_.scalapb.descriptors.PByteString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = rep.proto.rc2.TransactionResult.StatesGetEntry
  }
  
  object StatesGetEntry extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult.StatesGetEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult.StatesGetEntry] = this
    implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.TransactionResult.StatesGetEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        rep.proto.rc2.TransactionResult.StatesGetEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = rep.proto.rc2.TransactionResult.javaDescriptor.getNestedTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = rep.proto.rc2.TransactionResult.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = rep.proto.rc2.TransactionResult.StatesGetEntry(
      key = "",
      value = _root_.com.google.protobuf.ByteString.EMPTY
    )
    implicit class StatesGetEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.TransactionResult.StatesGetEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.TransactionResult.StatesGetEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesGetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] =
      _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesGetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)](__m => (__m.key, __m.value))(__p => rep.proto.rc2.TransactionResult.StatesGetEntry(__p._1, __p._2))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.com.google.protobuf.ByteString,
      unknownFields: _root_.scalapb.UnknownFieldSet
    ): _root_.rep.proto.rc2.TransactionResult.StatesGetEntry = _root_.rep.proto.rc2.TransactionResult.StatesGetEntry(
      key,
      value,
      unknownFields
    )
  }
  
  @SerialVersionUID(0L)
  final case class StatesSetEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.Message[StatesSetEntry] with scalapb.lenses.Updatable[StatesSetEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (__value != "") {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = value
          if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = value
          if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
            _output__.writeBytes(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.TransactionResult.StatesSetEntry = {
        var __key = this.key
        var __value = this.value
        var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readString()
            case 18 =>
              __value = _input__.readBytes()
            case tag =>
              if (_unknownFields__ == null) {
                _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
              }
              _unknownFields__.parseField(tag, _input__)
          }
        }
        rep.proto.rc2.TransactionResult.StatesSetEntry(
            key = __key,
            value = __value,
            unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
        )
      }
      def withKey(__v: _root_.scala.Predef.String): StatesSetEntry = copy(key = __v)
      def withValue(__v: _root_.com.google.protobuf.ByteString): StatesSetEntry = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = value
            if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => _root_.scalapb.descriptors.PByteString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = rep.proto.rc2.TransactionResult.StatesSetEntry
  }
  
  object StatesSetEntry extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult.StatesSetEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult.StatesSetEntry] = this
    implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.TransactionResult.StatesSetEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        rep.proto.rc2.TransactionResult.StatesSetEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = rep.proto.rc2.TransactionResult.javaDescriptor.getNestedTypes.get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = rep.proto.rc2.TransactionResult.scalaDescriptor.nestedMessages(1)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = rep.proto.rc2.TransactionResult.StatesSetEntry(
      key = "",
      value = _root_.com.google.protobuf.ByteString.EMPTY
    )
    implicit class StatesSetEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.TransactionResult.StatesSetEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.TransactionResult.StatesSetEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesSetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] =
      _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesSetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)](__m => (__m.key, __m.value))(__p => rep.proto.rc2.TransactionResult.StatesSetEntry(__p._1, __p._2))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.com.google.protobuf.ByteString,
      unknownFields: _root_.scalapb.UnknownFieldSet
    ): _root_.rep.proto.rc2.TransactionResult.StatesSetEntry = _root_.rep.proto.rc2.TransactionResult.StatesSetEntry(
      key,
      value,
      unknownFields
    )
  }
  
  @SerialVersionUID(0L)
  final case class StatesDelEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.Message[StatesDelEntry] with scalapb.lenses.Updatable[StatesDelEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (__value != "") {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = value
          if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = value
          if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
            _output__.writeBytes(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.TransactionResult.StatesDelEntry = {
        var __key = this.key
        var __value = this.value
        var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readString()
            case 18 =>
              __value = _input__.readBytes()
            case tag =>
              if (_unknownFields__ == null) {
                _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
              }
              _unknownFields__.parseField(tag, _input__)
          }
        }
        rep.proto.rc2.TransactionResult.StatesDelEntry(
            key = __key,
            value = __value,
            unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
        )
      }
      def withKey(__v: _root_.scala.Predef.String): StatesDelEntry = copy(key = __v)
      def withValue(__v: _root_.com.google.protobuf.ByteString): StatesDelEntry = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = value
            if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => _root_.scalapb.descriptors.PByteString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = rep.proto.rc2.TransactionResult.StatesDelEntry
  }
  
  object StatesDelEntry extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult.StatesDelEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.TransactionResult.StatesDelEntry] = this
    implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.TransactionResult.StatesDelEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        rep.proto.rc2.TransactionResult.StatesDelEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = rep.proto.rc2.TransactionResult.javaDescriptor.getNestedTypes.get(2)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = rep.proto.rc2.TransactionResult.scalaDescriptor.nestedMessages(2)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = rep.proto.rc2.TransactionResult.StatesDelEntry(
      key = "",
      value = _root_.com.google.protobuf.ByteString.EMPTY
    )
    implicit class StatesDelEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.TransactionResult.StatesDelEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.TransactionResult.StatesDelEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesDelEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] =
      _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesDelEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)](__m => (__m.key, __m.value))(__p => rep.proto.rc2.TransactionResult.StatesDelEntry(__p._1, __p._2))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.com.google.protobuf.ByteString,
      unknownFields: _root_.scalapb.UnknownFieldSet
    ): _root_.rep.proto.rc2.TransactionResult.StatesDelEntry = _root_.rep.proto.rc2.TransactionResult.StatesDelEntry(
      key,
      value,
      unknownFields
    )
  }
  
  implicit class TransactionResultLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.TransactionResult]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.TransactionResult](_l) {
    def txId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.txId)((c_, f_) => c_.copy(txId = f_))
    def statesGet: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = field(_.statesGet)((c_, f_) => c_.copy(statesGet = f_))
    def statesSet: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = field(_.statesSet)((c_, f_) => c_.copy(statesSet = f_))
    def statesDel: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = field(_.statesDel)((c_, f_) => c_.copy(statesDel = f_))
    def err: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ActionResult] = field(_.getErr)((c_, f_) => c_.copy(err = Option(f_)))
    def optionalErr: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[rep.proto.rc2.ActionResult]] = field(_.err)((c_, f_) => c_.copy(err = f_))
  }
  final val TXID_FIELD_NUMBER = 1
  final val STATES_GET_FIELD_NUMBER = 2
  final val STATES_SET_FIELD_NUMBER = 3
  final val STATES_DEL_FIELD_NUMBER = 4
  final val ERR_FIELD_NUMBER = 5
  @transient
  private val _typemapper_statesGet: _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesGetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] = implicitly[_root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesGetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]]
  @transient
  private val _typemapper_statesSet: _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesSetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] = implicitly[_root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesSetEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]]
  @transient
  private val _typemapper_statesDel: _root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesDelEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] = implicitly[_root_.scalapb.TypeMapper[rep.proto.rc2.TransactionResult.StatesDelEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]]
  def of(
    txId: _root_.scala.Predef.String,
    statesGet: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString],
    statesSet: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString],
    statesDel: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString],
    err: _root_.scala.Option[rep.proto.rc2.ActionResult],
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.TransactionResult = _root_.rep.proto.rc2.TransactionResult(
    txId,
    statesGet,
    statesSet,
    statesDel,
    err,
    unknownFields
  )
}
