// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 签名交易
  *
  * @param cid
  *  store ChaincodeID as bytes so its encrypted value can be stored
  * @param gasLimit
  *  可选，如果有设置按照预设的资源消耗,超出则终止执行；否则不限制。
  * @param oid
  *  重放举证：交易实例Id，可选, 导出实例时，要求提供同一区块内部，
  *  同一合约实例的交易顺序及证明
  *  默认空为全局的实例id，
  * @param signature
  *  交易签发者签名
  */
@SerialVersionUID(0L)
final case class Transaction(
    id: _root_.scala.Predef.String = "",
    `type`: rep.proto.rc2.Transaction.Type = rep.proto.rc2.Transaction.Type.UNDEFINED,
    cid: _root_.scala.Option[rep.proto.rc2.ChaincodeId] = _root_.scala.None,
    para: rep.proto.rc2.Transaction.Para = rep.proto.rc2.Transaction.Para.Empty,
    gasLimit: _root_.scala.Int = 0,
    oid: _root_.scala.Predef.String = "",
    signature: _root_.scala.Option[rep.proto.rc2.Signature] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[Transaction] with scalapb.lenses.Updatable[Transaction] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = `type`
        if (__value != rep.proto.rc2.Transaction.Type.UNDEFINED) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(2, __value.value)
        }
      };
      if (cid.isDefined) {
        val __value = cid.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (para.spec.isDefined) {
        val __value = para.spec.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (para.ipt.isDefined) {
        val __value = para.ipt.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (para.state.isDefined) {
        val __value = para.state.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(6, __value)
      };
      
      {
        val __value = gasLimit
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(7, __value)
        }
      };
      
      {
        val __value = oid
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
        }
      };
      if (signature.isDefined) {
        val __value = signature.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = `type`
        if (__v != rep.proto.rc2.Transaction.Type.UNDEFINED) {
          _output__.writeEnum(2, __v.value)
        }
      };
      cid.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      para.spec.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      para.ipt.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      para.state.foreach { __v =>
        val __m = __v
        _output__.writeBool(6, __m)
      };
      {
        val __v = gasLimit
        if (__v != 0) {
          _output__.writeUInt32(7, __v)
        }
      };
      {
        val __v = oid
        if (__v != "") {
          _output__.writeString(8, __v)
        }
      };
      signature.foreach { __v =>
        val __m = __v
        _output__.writeTag(9, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.Transaction = {
      var __id = this.id
      var __type = this.`type`
      var __cid = this.cid
      var __gasLimit = this.gasLimit
      var __oid = this.oid
      var __signature = this.signature
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var __para = this.para
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __id = _input__.readString()
          case 16 =>
            __type = rep.proto.rc2.Transaction.Type.fromValue(_input__.readEnum())
          case 26 =>
            __cid = Option(_root_.scalapb.LiteParser.readMessage(_input__, __cid.getOrElse(rep.proto.rc2.ChaincodeId.defaultInstance)))
          case 34 =>
            __para = rep.proto.rc2.Transaction.Para.Spec(_root_.scalapb.LiteParser.readMessage(_input__, para.spec.getOrElse(rep.proto.rc2.ChaincodeDeploy.defaultInstance)))
          case 42 =>
            __para = rep.proto.rc2.Transaction.Para.Ipt(_root_.scalapb.LiteParser.readMessage(_input__, para.ipt.getOrElse(rep.proto.rc2.ChaincodeInput.defaultInstance)))
          case 48 =>
            __para = rep.proto.rc2.Transaction.Para.State(_input__.readBool())
          case 56 =>
            __gasLimit = _input__.readUInt32()
          case 66 =>
            __oid = _input__.readString()
          case 74 =>
            __signature = Option(_root_.scalapb.LiteParser.readMessage(_input__, __signature.getOrElse(rep.proto.rc2.Signature.defaultInstance)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.Transaction(
          id = __id,
          `type` = __type,
          cid = __cid,
          gasLimit = __gasLimit,
          oid = __oid,
          signature = __signature,
          para = __para,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withId(__v: _root_.scala.Predef.String): Transaction = copy(id = __v)
    def withType(__v: rep.proto.rc2.Transaction.Type): Transaction = copy(`type` = __v)
    def getCid: rep.proto.rc2.ChaincodeId = cid.getOrElse(rep.proto.rc2.ChaincodeId.defaultInstance)
    def clearCid: Transaction = copy(cid = _root_.scala.None)
    def withCid(__v: rep.proto.rc2.ChaincodeId): Transaction = copy(cid = Option(__v))
    def getSpec: rep.proto.rc2.ChaincodeDeploy = para.spec.getOrElse(rep.proto.rc2.ChaincodeDeploy.defaultInstance)
    def withSpec(__v: rep.proto.rc2.ChaincodeDeploy): Transaction = copy(para = rep.proto.rc2.Transaction.Para.Spec(__v))
    def getIpt: rep.proto.rc2.ChaincodeInput = para.ipt.getOrElse(rep.proto.rc2.ChaincodeInput.defaultInstance)
    def withIpt(__v: rep.proto.rc2.ChaincodeInput): Transaction = copy(para = rep.proto.rc2.Transaction.Para.Ipt(__v))
    def getState: _root_.scala.Boolean = para.state.getOrElse(false)
    def withState(__v: _root_.scala.Boolean): Transaction = copy(para = rep.proto.rc2.Transaction.Para.State(__v))
    def withGasLimit(__v: _root_.scala.Int): Transaction = copy(gasLimit = __v)
    def withOid(__v: _root_.scala.Predef.String): Transaction = copy(oid = __v)
    def getSignature: rep.proto.rc2.Signature = signature.getOrElse(rep.proto.rc2.Signature.defaultInstance)
    def clearSignature: Transaction = copy(signature = _root_.scala.None)
    def withSignature(__v: rep.proto.rc2.Signature): Transaction = copy(signature = Option(__v))
    def clearPara: Transaction = copy(para = rep.proto.rc2.Transaction.Para.Empty)
    def withPara(__v: rep.proto.rc2.Transaction.Para): Transaction = copy(para = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = `type`.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 3 => cid.orNull
        case 4 => para.spec.orNull
        case 5 => para.ipt.orNull
        case 6 => para.state.orNull
        case 7 => {
          val __t = gasLimit
          if (__t != 0) __t else null
        }
        case 8 => {
          val __t = oid
          if (__t != "") __t else null
        }
        case 9 => signature.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(id)
        case 2 => _root_.scalapb.descriptors.PEnum(`type`.scalaValueDescriptor)
        case 3 => cid.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => para.spec.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 5 => para.ipt.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 6 => para.state.map(_root_.scalapb.descriptors.PBoolean).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 7 => _root_.scalapb.descriptors.PInt(gasLimit)
        case 8 => _root_.scalapb.descriptors.PString(oid)
        case 9 => signature.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.Transaction
}

object Transaction extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.Transaction] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.Transaction] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.Transaction] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.Transaction(
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        `type` = rep.proto.rc2.Transaction.Type.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(rep.proto.rc2.Transaction.Type.UNDEFINED.scalaValueDescriptor).number),
        cid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.ChaincodeId]]),
        gasLimit = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        oid = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        signature = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.Signature]]),
        para = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.ChaincodeDeploy]]).map(rep.proto.rc2.Transaction.Para.Spec)
            .orElse[rep.proto.rc2.Transaction.Para](__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[rep.proto.rc2.ChaincodeInput]]).map(rep.proto.rc2.Transaction.Para.Ipt))
            .orElse[rep.proto.rc2.Transaction.Para](__fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Boolean]]).map(rep.proto.rc2.Transaction.Para.State))
            .getOrElse(rep.proto.rc2.Transaction.Para.Empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(17)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(17)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = rep.proto.rc2.ChaincodeId
      case 4 => __out = rep.proto.rc2.ChaincodeDeploy
      case 5 => __out = rep.proto.rc2.ChaincodeInput
      case 9 => __out = rep.proto.rc2.Signature
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 2 => rep.proto.rc2.Transaction.Type
    }
  }
  lazy val defaultInstance = rep.proto.rc2.Transaction(
    id = "",
    `type` = rep.proto.rc2.Transaction.Type.UNDEFINED,
    cid = _root_.scala.None,
    gasLimit = 0,
    oid = "",
    signature = _root_.scala.None,
    para = rep.proto.rc2.Transaction.Para.Empty
  )
  sealed trait Type extends _root_.scalapb.GeneratedEnum {
    type EnumType = Type
    def isUndefined: _root_.scala.Boolean = false
    def isChaincodeDeploy: _root_.scala.Boolean = false
    def isChaincodeInvoke: _root_.scala.Boolean = false
    def isChaincodeSetState: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[Type] = rep.proto.rc2.Transaction.Type
    final def asRecognized: _root_.scala.Option[rep.proto.rc2.Transaction.Type.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[rep.proto.rc2.Transaction.Type.Recognized])
  }
  
  object Type extends _root_.scalapb.GeneratedEnumCompanion[Type] {
    sealed trait Recognized extends Type
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Type] = this
    @SerialVersionUID(0L)
    case object UNDEFINED extends Type with Type.Recognized {
      val value = 0
      val index = 0
      val name = "UNDEFINED"
      override def isUndefined: _root_.scala.Boolean = true
    }
    
    /** 用于部署合约的签名交易
      */
    @SerialVersionUID(0L)
    case object CHAINCODE_DEPLOY extends Type with Type.Recognized {
      val value = 1
      val index = 1
      val name = "CHAINCODE_DEPLOY"
      override def isChaincodeDeploy: _root_.scala.Boolean = true
    }
    
    /** 用于调用合约方法的签名交易
      */
    @SerialVersionUID(0L)
    case object CHAINCODE_INVOKE extends Type with Type.Recognized {
      val value = 2
      val index = 2
      val name = "CHAINCODE_INVOKE"
      override def isChaincodeInvoke: _root_.scala.Boolean = true
    }
    
    /** 用于启用/禁用合约的签名交易
      */
    @SerialVersionUID(0L)
    case object CHAINCODE_SET_STATE extends Type with Type.Recognized {
      val value = 3
      val index = 3
      val name = "CHAINCODE_SET_STATE"
      override def isChaincodeSetState: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends Type with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(UNDEFINED, CHAINCODE_DEPLOY, CHAINCODE_INVOKE, CHAINCODE_SET_STATE)
    def fromValue(value: _root_.scala.Int): Type = value match {
      case 0 => UNDEFINED
      case 1 => CHAINCODE_DEPLOY
      case 2 => CHAINCODE_INVOKE
      case 3 => CHAINCODE_SET_STATE
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = rep.proto.rc2.Transaction.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = rep.proto.rc2.Transaction.scalaDescriptor.enums(0)
  }
  sealed trait Para extends _root_.scalapb.GeneratedOneof {
    def isEmpty: _root_.scala.Boolean = false
    def isDefined: _root_.scala.Boolean = true
    def isSpec: _root_.scala.Boolean = false
    def isIpt: _root_.scala.Boolean = false
    def isState: _root_.scala.Boolean = false
    def spec: _root_.scala.Option[rep.proto.rc2.ChaincodeDeploy] = _root_.scala.None
    def ipt: _root_.scala.Option[rep.proto.rc2.ChaincodeInput] = _root_.scala.None
    def state: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None
  }
  object Para extends {
    @SerialVersionUID(0L)
    case object Empty extends rep.proto.rc2.Transaction.Para {
      type ValueType = _root_.scala.Nothing
      override def isEmpty: _root_.scala.Boolean = true
      override def isDefined: _root_.scala.Boolean = false
      override def number: _root_.scala.Int = 0
      override def value: _root_.scala.Nothing = throw new java.util.NoSuchElementException("Empty.value")
    }
  
    @SerialVersionUID(0L)
    final case class Spec(value: rep.proto.rc2.ChaincodeDeploy) extends rep.proto.rc2.Transaction.Para {
      type ValueType = rep.proto.rc2.ChaincodeDeploy
      override def isSpec: _root_.scala.Boolean = true
      override def spec: _root_.scala.Option[rep.proto.rc2.ChaincodeDeploy] = Some(value)
      override def number: _root_.scala.Int = 4
    }
    @SerialVersionUID(0L)
    final case class Ipt(value: rep.proto.rc2.ChaincodeInput) extends rep.proto.rc2.Transaction.Para {
      type ValueType = rep.proto.rc2.ChaincodeInput
      override def isIpt: _root_.scala.Boolean = true
      override def ipt: _root_.scala.Option[rep.proto.rc2.ChaincodeInput] = Some(value)
      override def number: _root_.scala.Int = 5
    }
    @SerialVersionUID(0L)
    final case class State(value: _root_.scala.Boolean) extends rep.proto.rc2.Transaction.Para {
      type ValueType = _root_.scala.Boolean
      override def isState: _root_.scala.Boolean = true
      override def state: _root_.scala.Option[_root_.scala.Boolean] = Some(value)
      override def number: _root_.scala.Int = 6
    }
  }
  implicit class TransactionLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Transaction]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.Transaction](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Transaction.Type] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
    def cid: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeId] = field(_.getCid)((c_, f_) => c_.copy(cid = Option(f_)))
    def optionalCid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[rep.proto.rc2.ChaincodeId]] = field(_.cid)((c_, f_) => c_.copy(cid = f_))
    def spec: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeDeploy] = field(_.getSpec)((c_, f_) => c_.copy(para = rep.proto.rc2.Transaction.Para.Spec(f_)))
    def ipt: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.ChaincodeInput] = field(_.getIpt)((c_, f_) => c_.copy(para = rep.proto.rc2.Transaction.Para.Ipt(f_)))
    def state: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getState)((c_, f_) => c_.copy(para = rep.proto.rc2.Transaction.Para.State(f_)))
    def gasLimit: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.gasLimit)((c_, f_) => c_.copy(gasLimit = f_))
    def oid: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.oid)((c_, f_) => c_.copy(oid = f_))
    def signature: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Signature] = field(_.getSignature)((c_, f_) => c_.copy(signature = Option(f_)))
    def optionalSignature: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[rep.proto.rc2.Signature]] = field(_.signature)((c_, f_) => c_.copy(signature = f_))
    def para: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.Transaction.Para] = field(_.para)((c_, f_) => c_.copy(para = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val TYPE_FIELD_NUMBER = 2
  final val CID_FIELD_NUMBER = 3
  final val SPEC_FIELD_NUMBER = 4
  final val IPT_FIELD_NUMBER = 5
  final val STATE_FIELD_NUMBER = 6
  final val GAS_LIMIT_FIELD_NUMBER = 7
  final val OID_FIELD_NUMBER = 8
  final val SIGNATURE_FIELD_NUMBER = 9
  def of(
    id: _root_.scala.Predef.String,
    `type`: rep.proto.rc2.Transaction.Type,
    cid: _root_.scala.Option[rep.proto.rc2.ChaincodeId],
    para: rep.proto.rc2.Transaction.Para,
    gasLimit: _root_.scala.Int,
    oid: _root_.scala.Predef.String,
    signature: _root_.scala.Option[rep.proto.rc2.Signature],
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.Transaction = _root_.rep.proto.rc2.Transaction(
    id,
    `type`,
    cid,
    para,
    gasLimit,
    oid,
    signature,
    unknownFields
  )
}
