// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package rep.proto.rc2

/** 可验证凭据状态(Verifiable Credential, VC)
  *
  * @param version
  *   本数据结构的版本
  * @param id
  *   VC唯一标识
  * @param status
  *   VC所处状态，使用者自行定义
  * @param revokedClaimIndex
  *   VC中已被撤销的凭据属性编号
  * @param creator
  *   VC签发者的did标识，用于更新操作的权限控制
  */
@SerialVersionUID(0L)
final case class VerCreStatus(
    version: _root_.scala.Predef.String = "",
    id: _root_.scala.Predef.String = "",
    status: _root_.scala.Predef.String = "",
    revokedClaimIndex: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    creator: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[VerCreStatus] with scalapb.lenses.Updatable[VerCreStatus] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = version
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = id
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = status
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      revokedClaimIndex.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
      }
      
      {
        val __value = creator
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = version
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = id
        if (__v != "") {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = status
        if (__v != "") {
          _output__.writeString(3, __v)
        }
      };
      revokedClaimIndex.foreach { __v =>
        val __m = __v
        _output__.writeString(4, __m)
      };
      {
        val __v = creator
        if (__v != "") {
          _output__.writeString(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): rep.proto.rc2.VerCreStatus = {
      var __version = this.version
      var __id = this.id
      var __status = this.status
      val __revokedClaimIndex = (_root_.scala.collection.immutable.Vector.newBuilder[_root_.scala.Predef.String] ++= this.revokedClaimIndex)
      var __creator = this.creator
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __version = _input__.readString()
          case 18 =>
            __id = _input__.readString()
          case 26 =>
            __status = _input__.readString()
          case 34 =>
            __revokedClaimIndex += _input__.readString()
          case 42 =>
            __creator = _input__.readString()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(this.unknownFields)
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      rep.proto.rc2.VerCreStatus(
          version = __version,
          id = __id,
          status = __status,
          revokedClaimIndex = __revokedClaimIndex.result(),
          creator = __creator,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    def withVersion(__v: _root_.scala.Predef.String): VerCreStatus = copy(version = __v)
    def withId(__v: _root_.scala.Predef.String): VerCreStatus = copy(id = __v)
    def withStatus(__v: _root_.scala.Predef.String): VerCreStatus = copy(status = __v)
    def clearRevokedClaimIndex = copy(revokedClaimIndex = _root_.scala.Seq.empty)
    def addRevokedClaimIndex(__vs: _root_.scala.Predef.String*): VerCreStatus = addAllRevokedClaimIndex(__vs)
    def addAllRevokedClaimIndex(__vs: Iterable[_root_.scala.Predef.String]): VerCreStatus = copy(revokedClaimIndex = revokedClaimIndex ++ __vs)
    def withRevokedClaimIndex(__v: _root_.scala.Seq[_root_.scala.Predef.String]): VerCreStatus = copy(revokedClaimIndex = __v)
    def withCreator(__v: _root_.scala.Predef.String): VerCreStatus = copy(creator = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = version
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = status
          if (__t != "") __t else null
        }
        case 4 => revokedClaimIndex
        case 5 => {
          val __t = creator
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(version)
        case 2 => _root_.scalapb.descriptors.PString(id)
        case 3 => _root_.scalapb.descriptors.PString(status)
        case 4 => _root_.scalapb.descriptors.PRepeated(revokedClaimIndex.iterator.map(_root_.scalapb.descriptors.PString).toVector)
        case 5 => _root_.scalapb.descriptors.PString(creator)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = rep.proto.rc2.VerCreStatus
}

object VerCreStatus extends scalapb.GeneratedMessageCompanion[rep.proto.rc2.VerCreStatus] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[rep.proto.rc2.VerCreStatus] = this
  implicit def messageReads: _root_.scalapb.descriptors.Reads[rep.proto.rc2.VerCreStatus] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      rep.proto.rc2.VerCreStatus(
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        status = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        revokedClaimIndex = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        creator = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Rc2Proto.javaDescriptor.getMessageTypes.get(9)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Rc2Proto.scalaDescriptor.messages(9)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = rep.proto.rc2.VerCreStatus(
    version = "",
    id = "",
    status = "",
    revokedClaimIndex = _root_.scala.Seq.empty,
    creator = ""
  )
  implicit class VerCreStatusLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, rep.proto.rc2.VerCreStatus]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, rep.proto.rc2.VerCreStatus](_l) {
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def status: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.status)((c_, f_) => c_.copy(status = f_))
    def revokedClaimIndex: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.revokedClaimIndex)((c_, f_) => c_.copy(revokedClaimIndex = f_))
    def creator: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.creator)((c_, f_) => c_.copy(creator = f_))
  }
  final val VERSION_FIELD_NUMBER = 1
  final val ID_FIELD_NUMBER = 2
  final val STATUS_FIELD_NUMBER = 3
  final val REVOKEDCLAIMINDEX_FIELD_NUMBER = 4
  final val CREATOR_FIELD_NUMBER = 5
  def of(
    version: _root_.scala.Predef.String,
    id: _root_.scala.Predef.String,
    status: _root_.scala.Predef.String,
    revokedClaimIndex: _root_.scala.Seq[_root_.scala.Predef.String],
    creator: _root_.scala.Predef.String,
    unknownFields: _root_.scalapb.UnknownFieldSet
  ): _root_.rep.proto.rc2.VerCreStatus = _root_.rep.proto.rc2.VerCreStatus(
    version,
    id,
    status,
    revokedClaimIndex,
    creator,
    unknownFields
  )
}
